# Modul 20 - 25

def load_part5(add_module):
    # Modul 20: Eksperimen Software t-Test & Mann-Whitney U
    add_module(
        20, "Eksperimen Software t-Test & Mann-Whitney U", "Buku 2",
        [
            ("Uji statistik parametrik yang paling tepat digunakan untuk membandingkan latensi eksekusi endpoint API pada 50 modul perangkat lunak SEBELUM dan SESUDAH dilakukan refaktorisasi kode (data berpasangan) adalah:",
             {"A": "Independent Two-Sample t-Test", "B": "Paired Samples t-Test (Uji-t Berpasangan)", "C": "One-Way ANOVA", "D": "Uji Chi-Square", "E": "Uji Mann-Whitney U"}, "B",
             "Paired Samples t-Test menguji perbedaan rata-rata selisih (d_i = Before - After) pada subjek yang sama sebelum dan sesudah intervensi/perlakuan refaktorisasi."),
            ("Jika asumsi normalitas data selisih waktu eksekusi dilanggar secara parah (sangat tidak normal), uji komparasi non-parametrik berpasangan yang tepat sebagai alternatif Paired t-Test adalah:",
             {"A": "Uji Wilcoxon Signed-Rank", "B": "Uji Mann-Whitney U", "C": "Uji Kruskal-Wallis", "D": "Uji Levene", "E": "Uji Pearson"}, "A",
             "Wilcoxon Signed-Rank Test adalah padanan non-parametrik dari Paired t-Test yang menguji perbedaan median data berpasangan berbasis peringkat tanda."),
            ("Uji Mann-Whitney U (Wilcoxon Rank-Sum Test) digunakan sebagai alternatif non-parametrik untuk membandingkan:",
             {"A": "Satu sampel terhadap nilai konstanta", "B": "Dua kelompok sampel independen yang tidak berdistribusi normal", "C": "Tiga kelompok sampel berpasangan", "D": "Variabel kategorikal biner murni", "E": "Hubungan korelasi multivariat"}, "B",
             "Mann-Whitney U membandingkan peringkat nilai antara dua kelompok independen (misal: Kecepatan Arsitektur Monolith vs Microservices) tanpa mensyaratkan asumsi distribusi normal."),
            ("Metrik Effect Size 'Cohen's d' digunakan dalam eksperimen rekayasa perangkat lunak untuk mengukur:",
             {"A": "Tingkat signifikansi p-value semata", "B": "Besaran magnitudo praktis dari efek perbedaan rata-rata terstandarisasi dalam satuan standar deviasi", "C": "Jumlah baris kode yang direfaktor", "D": "Persentase error rate server", "E": "Ukuran memori RAM terpakai"}, "B",
             "Cohen's d = (Mean_1 - Mean_2) / Pooled_Std mengukur seberapa besar dampak praktis perbaikan performa sistem secara nyata, terlepas dari ukuran sampel n (d = 0.2 kecil, 0.5 sedang, 0.8 besar).")
        ],
        [
            ("Apakah hipotesis nol (H0) pada Paired Samples t-Test untuk pengujian efek refaktorisasi terhadap latensi API (mu_before vs mu_after)?",
             "H0: mu_before = mu_after (atau mu_d = 0, tidak ada perbedaan latensi rata-rata sebelum dan sesudah refaktorisasi)", "H0 selalu menyatakan bahwa rata-rata selisih adalah nol (ketiadaan efek perlakuan)."),
            ("Jika nilai Cohen's d dalam suatu eksperimen optimasi query database adalah d = 1.25, bagaimanakah interpretasi magnitudo efeknya?",
             "Efek sangat besar / kuat (Very Large Effect Size, d >= 0.80)", "Nilai Cohen's d > 0.80 diklasifikasikan sebagai efek yang sangat besar dan berdampak praktis tinggi di industri."),
            ("Sebutkan fungsi dalam pustaka SciPy Python untuk mengeksekusi Paired Samples t-Test secara otomatis!",
             "scipy.stats.ttest_rel(before_data, after_data)", "Fungsi ttest_rel menghitung uji-t untuk dua sampel berpasangan terkait (related samples)."),
            ("Sebutkan fungsi dalam pustaka SciPy Python untuk mengeksekusi uji non-parametrik Mann-Whitney U!",
             "scipy.stats.mannwhitneyu(group1, group2)", "Fungsi mannwhitneyu membandingkan dua kelompok data independen secara non-parametrik.")
        ],
        [
            ("Diberikan data latensi eksekusi 6 query database (dalam ms) Sebelum dan Sesudah refaktorisasi indeks:\n- Query 1: Before = 120, After = 40 (d = 80)\n- Query 2: Before = 150, After = 50 (d = 100)\n- Query 3: Before = 110, After = 40 (d = 70)\n- Query 4: Before = 180, After = 60 (d = 120)\n- Query 5: Before = 140, After = 50 (d = 90)\n- Query 6: Before = 160, After = 60 (d = 100)\nHitunglah: (a) Rata-rata selisih (d_bar) dan Standar Deviasi selisih (s_d), (b) Nilai t-hitung Paired t-Test, (c) Ujilah pada alpha = 0.05 apakah refaktorisasi menghasilkan penurunan latensi yang signifikan (Nilai kritis t_tabel df=5 adalah 2.015)!",
             "(a) Data Selisih d = [80, 100, 70, 120, 90, 100].\n- Total d = 560, n = 6. Rata-rata selisih d_bar = 560 / 6 = 93.33 ms.\n- Deviasi (d_i - d_bar): [-13.33, +6.67, -23.33, +26.67, -3.33, +6.67].\n- Kuadrat Deviasi: [177.69, 44.49, 544.29, 711.29, 11.09, 44.49]. Sum = 1533.35.\n- Varians s_d² = 1533.35 / (6 - 1) = 306.67. Standar Deviasi s_d = sqrt(306.67) = 17.51 ms.\n(b) Standar Error SE = s_d / sqrt(n) = 17.51 / sqrt(6) = 17.51 / 2.4495 = 7.15 ms.\n- Nilai t-hitung = d_bar / SE = 93.33 / 7.15 = +13.05.\n(c) Kesimpulan: Karena t-hitung (+13.05) > t-tabel (2.015), Tolak H0 (p-value < 0.0001). Refaktorisasi indeks query terbukti secara statistik sangat signifikan menurunkan latensi eksekusi rata-rata sebesar 93.33 ms.",
             "Bobot 100: Perhitungan d_bar dan s_d tepat (35%), perhitungan t-hitung tepat (35%), pengujian hipotesis dan kesimpulan tepat (30%)."),
            ("Jelaskan mengapa dalam riset empiris rekayasa perangkat lunak modern, pelaporan p-value semata dianggap tidak cukup dan WAJIB disertai dengan pelaporan Effect Size (seperti Cohen's d)?",
             "Kelemahan p-value semata: 1) p-value sangat bergantung pada ukuran sampel (Sample Size Dependency). Dengan sampel yang sangat besar (misal n = 1.000.000 request), perbedaan latensi yang sangat kecil dan sepele (misal 0.001 ms) akan menghasilkan p-value < 0.0001 (sangat signifikan secara statistik), padahal perbaikan 0.001 ms tidak memiliki dampak praktis apapun bagi bisnis.\n2) p-value tidak memberikan informasi mengenai magnitudo atau besaran efek perbaikan.\nKeunggulan Effect Size (Cohen's d): 1) Mengukur besaran dampak praktis yang sebenarnya (Practical Significance) bebas dari ukuran sampel. 2) Memungkinkan perbandingan efektivitas refaktorisasi antar proyek yang berbeda melalui meta-analisis.",
             "Bobot 100: Analisis ketergantungan p-value thd ukuran sampel (40%), penjelasan konsep practical significance (35%), peran Cohen's d dalam riset empiris (25%)."),
            ("Kapan seorang software engineer harus memilih uji non-parametrik Mann-Whitney U daripada uji parametrik Two-Sample Independent t-Test? Jelaskan 3 kondisi spesifiknya!",
             "Kondisi Pemilihan Mann-Whitney U:\n1. Pelanggaran Asumsi Normalitas yang Parah: Ketika data metrik (misal latensi atau waktu penyelesaian tiket bug) berdistribusi sangat menceng (skewed) atau memiliki ekor tebal (fat-tailed) dan transformasi data tidak berhasil menormalkannya.\n2. Keberadaan Outlier Ekstrem: Mann-Whitney U bekerja berbasis urutan peringkat (ranking), sehingga tidak terdistorsi oleh satu atau dua nilai outlier raksasa yang merusak nilai mean pada t-test.\n3. Skala Data Berskala Ordinal: Jika data yang diuji berupa data peringkat atau skor kuesioner skala Likert (1-5) yang tidak memiliki sifat jarak metrik konstan.",
             "Bobot 100: Penjelasan kondisi non-normalitas (35%), ketahanan terhadap outlier via ranking (35%), skala data ordinal (30%)."),
            ("Tuliskan fungsi Python lengkap untuk: (1) Menguji normalitas data selisih Before-After dengan Shapiro-Wilk, (2) Memilih secara otomatis antara Paired t-Test (jika normal) atau Wilcoxon Signed-Rank Test (jika tidak normal), dan (3) Menghitung nilai Effect Size Cohen's d!",
             "Skrip Python:\nimport numpy as np, scipy.stats as stats\ndef automated_paired_experiment(before, after, alpha=0.05):\n    diff = np.array(before) - np.array(after)\n    # 1. Uji Normalitas Selisih\n    _, p_norm = stats.shapiro(diff)\n    # 2. Pemilihan Uji Otomatis\n    if p_norm > alpha:\n        t_stat, p_val = stats.ttest_rel(before, after)\n        test_name = 'Paired t-Test (Parametrik)'\n    else:\n        t_stat, p_val = stats.wilcoxon(before, after)\n        test_name = 'Wilcoxon Signed-Rank (Non-Parametrik)'\n    # 3. Cohen's d Effect Size\n    d = np.mean(diff) / np.std(diff, ddof=1)\n    print(f'=== Hasil Eksperimen: {test_name} ===')\n    print(f'Statistik: {t_stat:.4f} | p-value: {p_val:.4e} | Cohen d: {d:.3f}')\n    return {'test': test_name, 'p_val': p_val, 'cohen_d': d}",
             "Bobot 100: Uji normalitas Shapiro-Wilk tepat (30%), percabangan otomatis t-test vs Wilcoxon tepat (40%), perhitungan Cohen's d tepat (30%).")
        ]
    )

    # Modul 21: Analisis Varians (ANOVA) Interaksi UI/UX
    add_module(
        21, "Analisis Varians (ANOVA) Interaksi UI/UX", "Buku 2",
        [
            ("Uji Two-Way ANOVA (ANOVA Faktorial Dua Jalur) digunakan dalam eksperimen evaluasi antarmuka perangkat lunak untuk menguji:",
             {"A": "Korelasi linier antara dua variabel", "B": "Pengaruh utama (Main Effects) dari dua faktor independen sekaligus efek interaksi (Interaction Effect) keduanya terhadap variabel dependen kontinu", "C": "Proporsi biner tabel kontingensi", "D": "Keandalan instrumen SUS", "E": "Reduksi dimensi fitur"}, "B",
             "Two-Way ANOVA menguji pengaruh Faktor A, Faktor B, serta Interaksi (A x B) secara simultan terhadap variabel terikat metrik kontinu."),
            ("Dalam eksperimen desain antarmuka, apa yang dimaksud dengan 'Efek Interaksi' (Interaction Effect) antara Faktor Tata Letak (Layout) dan Faktor Perangkat (Device)?",
             {"A": "Layout dan Device selalu bekerja secara independen", "B": "Pengaruh efektivitas suatu Layout terhadap waktu tugas pengguna bergantung pada jenis Device yang digunakan", "C": "Device menyebabkan Layout menjadi rusak", "D": "Waktu tugas selalu konstan di semua device", "E": "Layout tidak memiliki pengaruh apapun"}, "B",
             "Efek interaksi terjadi ketika dampak dari Faktor A terhadap target tidak sama di setiap tingkatan Faktor B (misal: Layout Sidebar sangat cepat di Desktop, tetapi sangat lambat di Mobile)."),
            ("Uji lanjutan Post-Hoc (seperti Tukey's HSD - Honestly Significant Difference) WAJIB dilakukan setelah uji ANOVA jika:",
             {"A": "Nilai F-hitung tidak signifikan (p > 0.05)", "B": "Nilai F-hitung signifikan (p < 0.05) pada faktor yang memiliki LEBIH DARI DUA tingkat perlakuan (k > 2 kelompok)", "C": "Ukuran sampel n = 2", "D": "Data berdistribusi binomial", "E": "Varians data tidak homogen"}, "B",
             "Jika ANOVA menunjukkan perbedaan signifikan pada k >= 3 kelompok, uji Post-Hoc Tukey HSD diperlukan untuk menentukan secara spesifik pasangan kelompok mana saja yang saling berbeda nyata."),
            ("Grafik visual yang paling jelas untuk mendeteksi adanya efek interaksi antara dua faktor dalam desain eksperimen faktorial adalah:",
             {"A": "Pie Chart", "B": "Interaction Plot (Grafik Garis Interaksi dengan garis yang saling berpotongan / non-paralel)", "C": "Histogram Frekuensi", "D": "Scatter Plot Bivariat", "E": "Boxplot Tunggal"}, "B",
             "Interaction Plot menampilkan garis respon rata-rata. Jika garis-garis antar kelompok saling bersilangan (berpotongan) atau tidak sejajar, itu adalah indikasi visual kuat adanya efek interaksi nyata.")
        ],
        [
            ("Diberikan eksperimen 2 faktor: Faktor Tata Letak (3 level) dan Faktor Perangkat (2 level). Berapakah jumlah total kombinasi perlakuan (treatment cells) dalam desain faktorial 3x2 tersebut?",
             "Total = 6 sel perlakuan (3 x 2 = 6)", "Desain faktorial 3x2 menghasilkan 3 x 2 = 6 kombinasi kelompok eksperimen."),
            ("Apakah hipotesis nol (H0) untuk pengujian Efek Interaksi (Interaction Effect A x B) pada Two-Way ANOVA?",
             "H0: Tidak ada efek interaksi antara Faktor A dan Faktor B terhadap variabel dependen", "H0 interaksi menyatakan bahwa pengaruh Faktor A bersifat seragam di seluruh level Faktor B."),
            ("Sebutkan fungsi dalam pustaka statsmodels Python yang digunakan untuk menghitung tabel ANOVA faktorial lengkap dari model OLS!",
             "statsmodels.api.stats.anova_lm(model_ols, typ=2)", "Fungsi anova_lm menghasilkan tabel ANOVA Tipe II / Tipe III lengkap dengan derajat kebebasan, Sum of Squares, F-stat, dan p-value."),
            ("Jika garis-garis pada Interaction Plot tampak sejajar sempurna (paralel), apakah terdapat efek interaksi yang signifikan?",
             "Tidak ada efek interaksi (Efek Interaksi = 0 / Tidak Signifikan)", "Garis paralel menandakan bahwa pengaruh faktor pertama konsisten sama di semua tingkatan faktor kedua (tidak ada interaksi).")
        ],
        [
            ("Jelaskan konsep Main Effects dan Interaction Effect dalam Two-Way ANOVA faktorial menggunakan studi kasus evaluasi waktu penyelesaian tugas antarmuka sistem: Faktor A = Navigasi (Sidebar vs Bottom Bar), Faktor B = Perangkat (Smartphone vs Desktop)!",
             "1. Main Effect Faktor A (Navigasi): Menguji apakah terdapat perbedaan rata-rata waktu tugas antara Navigasi Sidebar dan Bottom Bar secara keseluruhan, tanpa mempedulikan jenis perangkat.\n2. Main Effect Faktor B (Perangkat): Menguji apakah terdapat perbedaan rata-rata waktu tugas antara pengguna Smartphone dan Desktop secara keseluruhan, tanpa mempedulikan jenis navigasi.\n3. Interaction Effect (Navigasi x Perangkat): Menguji apakah keunggulan suatu navigasi bergantung pada perangkat yang digunakan. Contoh nyata: Pada Desktop, Navigasi Sidebar menghasilkan waktu tercepat karena layar lebar; namun pada Smartphone, Navigasi Bottom Bar menghasilkan waktu tercepat karena mudah dijangkau satu tangan. Jika pola ini terjadi, interaksi terbukti signifikan dan desainer tidak boleh memilih satu navigasi untuk semua perangkat (harus menerapkan responsif adaptif).",
             "Bobot 100: Penjelasan Main Effect A & B jelas (40%), penjelasan Interaction Effect mendalam dengan contoh UI/UX (40%), implikasi keputusan desain rekayasa (20%)."),
            ("Diberikan tabel Two-Way ANOVA eksperimen interaksi UI:\n- Faktor Layout (df = 2): SS = 120.0, MS = 60.0, F = 15.0, p = 0.0001\n- Faktor Device (df = 1): SS = 80.0, MS = 80.0, F = 20.0, p = 0.00005\n- Interaksi Layout x Device (df = 2): SS = 48.0, MS = 24.0, F = 6.0, p = 0.004\n- Error / Residual (df = 54): SS = 216.0, MS = 4.0\n(a) Jelaskan kesimpulan statistik untuk masing-masing Main Effect dan Efek Interaksi pada alpha = 0.05! (b) Mengapa ketika efek interaksi signifikan, interpretasi Main Effect tidak boleh diambil secara mentah-mentah?",
             "(a) Kesimpulan Statistik:\n1. Faktor Layout: F(2, 54) = 15.0, p = 0.0001 < 0.05 -> Main Effect Layout SIGNIFIKAN NYATA.\n2. Faktor Device: F(1, 54) = 20.0, p = 0.00005 < 0.05 -> Main Effect Device SIGNIFIKAN NYATA.\n3. Interaksi Layout x Device: F(2, 54) = 6.0, p = 0.004 < 0.05 -> Efek Interaksi SIGNIFIKAN NYATA.\n(b) Mengapa Main Effect Tidak Boleh Disimpulkan Mentah: Karena efek interaksi signifikan membuktikan bahwa pengaruh Layout tidak konsisten antar perangkat. Jika kita hanya melihat Main Effect bahwa 'Bottom Bar secara rata-rata paling cepat', kesimpulan ini bisa salah total pada pengguna Desktop di mana Sidebar justru jauh lebih unggul. Keputusan desain harus didasarkan pada Simple Main Effects per sub-kelompok perangkat.",
             "Bobot 100: Evaluasi statistik 3 komponen ANOVA tepat (50%), analisis kritis bahaya generalisasi main effect saat interaksi signifikan (50%)."),
            ("Jelaskan 3 asumsi matematis yang wajib dipenuhi sebelum melakukan analisis Two-Way ANOVA dan sebutkan uji diagnostik yang sesuai untuk masing-masing asumsi!",
             "1. Asumsi Normalitas Residual: Residual galat model harus berdistribusi normal di setiap sel kombinasi perlakuan. Uji Diagnostik: Uji Shapiro-Wilk pada residual dan inspeksi Normal Q-Q Plot.\n2. Asumsi Homogenitas Varians (Homoskedastisitas): Varians residual antar seluruh sel kelompok kombinasi harus homogen/sama. Uji Diagnostik: Uji Levene (Levene's Test for Equality of Variances).\n3. Asumsi Independensi Observasi: Setiap observasi sampel harus independen satu sama lain (dihasilkan melalui pengacakan alokasi subjek / random assignment yang ketat).",
             "Bobot 100: Penjelasan 3 asumsi ANOVA lengkap (50%), metode uji diagnostik untuk masing-masing asumsi tepat (50%)."),
            ("Tuliskan skrip Python menggunakan statsmodels dan seaborn untuk: (1) Membangun model OLS faktorial dengan formula 'waktu ~ C(layout) * C(device)', (2) Menghasilkan tabel anova_lm Tipe II, (3) Melakukan uji Post-Hoc Tukey HSD, dan (4) Membuat Interaction Plot garis interaksi!",
             "Skrip Python:\nimport statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nfrom statsmodels.stats.multicomp import pairwise_tukeyhsd\nimport matplotlib.pyplot as plt, seaborn as sns\n# 1. Model OLS & Tabel ANOVA\nmodel = ols('task_time ~ C(layout) * C(device)', data=df_ui).fit()\nanova_table = sm.stats.anova_lm(model, typ=2)\nprint('=== TABEL TWO-WAY ANOVA ===')\ndisplay(anova_table)\n# 2. Post-Hoc Tukey HSD\ntukey = pairwise_tukeyhsd(df_ui['task_time'], df_ui['layout'] + '_' + df_ui['device'], alpha=0.05)\nprint(tukey)\n# 3. Interaction Plot\nplt.figure(figsize=(8, 5))\nsns.pointplot(data=df_ui, x='layout', y='task_time', hue='device', markers=['o', 's'], linestyles=['-', '--'], capsize=0.1)\nplt.title('Interaction Plot: Layout x Device terhadap Waktu Tugas', fontweight='bold')\nplt.ylabel('Waktu Tugas (detik)'); plt.show()",
             "Bobot 100: Formula OLS faktorial dan anova_lm tepat (35%), pairwise_tukeyhsd tepat (30%), pointplot interaction plot rapi (35%).")
        ]
    )

    # Modul 22: Pemodelan Keandalan Software (SRE Kaplan-Meier)
    add_module(
        22, "Pemodelan Keandalan Software (SRE Kaplan-Meier)", "Buku 2",
        [
            ("Dalam analisis Software Reliability Engineering (SRE) dan analisis survival waktu hingga kegagalan (Time-to-Failure), data 'Right-Censored' didefinisikan sebagai:",
             {"A": "Data layanan yang mengalami crash di detik pertama", "B": "Layanan perangkat lunak yang masih berjalan normal tanpa mengalami kegagalan hingga batas akhir periode observasi pemantauan selesai", "C": "Data yang hilang akibat bug basis data", "D": "Nilai rata-rata latensi server", "E": "Data dengan nilai negatif"}, "B",
             "Right-Censoring terjadi saat periode pengamatan berakhir sebelum sistem mengalami crash/kegagalan, sehingga waktu kegagalan sejati sistem hanya diketahui 'setidaknya lebih lama dari durasi pemantauan T'."),
            ("Estimator non-parametrik standar yang digunakan untuk memperkirakan kurva fungsi ketahanan hidup / keandalan S(t) dari data right-censored adalah:",
             {"A": "Estimator Kaplan-Meier", "B": "Regresi Linier OLS", "C": "Metode K-Means", "D": "Skor Z-Score", "E": "Indeks Fleiss Kappa"}, "A",
             "Estimator Kaplan-Meier S(t) = Prod_{t_i <= t} [1 - (d_i / n_i)] menghitung probabilitas kumulatif sistem bertahan hidup melampaui waktu t dengan memperhitungkan data tersensor."),
            ("Uji hipotesis statistik non-parametrik yang digunakan untuk membandingkan apakah terdapat perbedaan kurva keandalan / survival yang signifikan antara dua arsitektur sistem (misal Monolith vs Microservices) adalah:",
             {"A": "Uji Log-Rank (Log-Rank Test)", "B": "Uji Durbin-Watson", "C": "Uji Shapiro-Wilk", "D": "Uji Korelasi Pearson", "E": "Uji VIF"}, "A",
             "Uji Log-Rank membandingkan frekuensi kegagalan teramati vs ekspektasi di setiap titik waktu diskrit untuk menguji kesamaan kurva survival antar dua populasi sistem."),
            ("Metrik keandalan Mean Time Between Failures (MTBF) pada sistem komputasi berdistribusi dihitung dari:",
             {"A": "Total waktu operasional uptime dibagi dengan total jumlah insiden kegagalan yang terjadi", "B": "Waktu perbaikan dibagi total server", "C": "Jumlah bug dikalikan 100", "D": "Rata-rata penggunaan RAM", "E": "Standar deviasi waktu restart"}, "A",
             "MTBF = Total Operational Uptime / Total Failures. Mengukur rata-rata interval waktu sistem mampu berjalan stabil tanpa gangguan di antara dua insiden kegagalan berturut-turut.")
        ],
        [
            ("Tuliskan formula produk batas Kaplan-Meier untuk mengestimasi fungsi keandalan S(t)!",
             "S(t) = Prod_{t_i <= t} (1 - d_i / n_i)", "d_i adalah jumlah kegagalan pada waktu t_i, dan n_i adalah jumlah unit sistem yang berisiko (at-risk) sesaat sebelum waktu t_i."),
            ("Jika sebuah server beroperasi selama total 7.200 jam uptime dan mengalami 4 kali insiden crash, berapakah nilai MTBF server tersebut?",
             "MTBF = 1.800 jam", "MTBF = 7.200 jam / 4 kegagalan = 1.800 jam per kegagalan."),
            ("Sebutkan pustaka Python standar untuk analisis survival dan pemodelan keandalan Kaplan-Meier!",
             "Lifelines (lifelines.KaplanMeierFitter)", "Pustaka Lifelines menyediakan modul KaplanMeierFitter, CoxPHFitter, dan logrank_test."),
            ("Apakah nilai probabilitas keandalan S(t) pada saat t = 0 (awal peluncuran sistem baru)?",
             "S(0) = 1.0 (atau 100%)", "Pada awal waktu t = 0, seluruh sistem diasumsikan masih beroperasi sempurna sehingga probabilitas keandalan adalah 1.0.")
        ],
        [
            ("Jelaskan mengapa metode statistik standar seperti regresi linier atau rata-rata sederhana TIDAK BISA digunakan untuk menganalisis data waktu kegagalan (Time-to-Failure) dalam SRE, dan mengapa analisis survival Kaplan-Meier mutlak diperlukan!",
             "1. Masalah Right-Censoring: Dalam pemantauan server selama 30 hari, banyak instance server yang TIDAK CRASH hingga hari ke-30 (data tersensor). Menghitung rata-rata sederhana dengan membuang data tersensor akan meremehkan keandalan sistem secara drastis (underestimate survival). Memperlakukan waktu sensor 30 hari sebagai waktu crash juga salah besar.\n2. Distribusi Sangat Menceng & Non-Normal: Waktu kegagalan perangkat lunak tidak pernah berdistribusi normal, melainkan mengikuti distribusi Weibull/Eksponensial dengan ekor panjang.\n3. Peran Kaplan-Meier: Kaplan-Meier mengestimasi probabilitas keandalan secara bertahap pada setiap titik waktu kegagalan diskrit dengan menyesuaikan jumlah sistem yang 'masih berisiko' (risk set), sehingga memanfaatkan 100% informasi dari data yang crash maupun data yang tersensor tanpa bias.",
             "Bobot 100: Analisis bahaya pengabaian right-censoring (40%), karakteristik non-normal time-to-failure (30%), keunggulan mekanisme risk-set Kaplan-Meier (30%)."),
            ("Diberikan data pengujian 10 instance layanan microservice selama 100 jam:\n- 20 jam: 1 crash\n- 40 jam: 1 crash\n- 50 jam: 2 instance tersensor (dihentikan untuk maintenance terjadwal)\n- 70 jam: 1 crash\n- 100 jam: 5 instance tersisa masih hidup normal (tersensor di akhir observasi)\nHitunglah estimasi fungsi keandalan Kaplan-Meier S(t) pada t = 20 jam, t = 40 jam, dan t = 70 jam!",
             "Langkah Perhitungan Kaplan-Meier:\n1. Titik Awal t = 0: n_0 = 10, S(0) = 1.0.\n2. Titik t = 20 jam: Jumlah berisiko n_1 = 10, crash d_1 = 1.\n   S(20) = S(0) * (1 - 1/10) = 1.0 * 0.90 = 0.900 (90.0%).\n3. Titik t = 40 jam: Sisa berisiko n_2 = 9, crash d_2 = 1.\n   S(40) = S(20) * (1 - 1/9) = 0.900 * (8/9) = 0.900 * 0.8889 = 0.800 (80.0%).\n4. Interval t = 50 jam: 2 instance tersensor, tidak ada crash. S(50) tetap 0.800, namun jumlah berisiko berkurang 2 menjadi n = 8 - 2 = 6 instance.\n5. Titik t = 70 jam: Sisa berisiko n_3 = 6, crash d_3 = 1.\n   S(70) = S(40) * (1 - 1/6) = 0.800 * (5/6) = 0.800 * 0.8333 = 0.6667 (66.67%).\nKesimpulan: Probabilitas sistem microservice mampu bertahan hidup tanpa crash melampaui 70 jam operasional adalah 66.67%.",
             "Bobot 100: Langkah perhitungan S(20) dan S(40) tepat (40%), penanganan sensor t=50 pada risk set tepat (30%), perhitungan S(70) & kesimpulan tepat (30%)."),
            ("Jelaskan prinsip kerja Uji Log-Rank (Log-Rank Test) dalam membuktikan apakah Arsitektur Microservices v2 secara signifikan lebih andal dibanding Arsitektur Monolith v1!",
             "Prinsip Kerja Uji Log-Rank:\n1. Penggabungan Data: Menggabungkan seluruh data kegagalan kedua kelompok arsitektur dan mengurutkan seluruh titik waktu kegagalan unik t_j.\n2. Tabel Kontingensi per Titik Waktu: Pada setiap waktu kegagalan t_j, hitung jumlah instance yang berisiko pada Monolith (n_1j) dan Microservice (n_2j), serta total kegagalan yang terjadi d_j.\n3. Frekuensi Ekspektasi (E_1j): Di bawah hipotesis nol H0 (keandalan kedua arsitektur identik), ekspektasi kegagalan pada Monolith adalah E_1j = d_j * (n_1j / (n_1j + n_2j)).\n4. Statistik Chi-Square Log-Rank: Akumulasikan selisih antara kegagalan teramati O_1 dan ekspektasi E_1: Z = (sum(O_1j - E_1j))² / sum(V_1j) yang mengikuti distribusi Chi-Square dengan df = 1.\n5. Keputusan: Jika p-value < 0.05, tolak H0. Terbukti secara statistik bahwa kurva keandalan Microservices berbeda signifikan dan lebih superior dibanding Monolith.",
             "Bobot 100: Penjelasan tabel kontingensi per waktu diskrit (40%), formulasi frekuensi ekspektasi O vs E (35%), penarikan kesimpulan Chi-Square log-rank (25%)."),
            ("Tuliskan skrip Python lengkap menggunakan pustaka lifelines untuk: (1) Melatih KaplanMeierFitter untuk 2 kelompok arsitektur, (2) Memplot kurva survival keandalan beserta confidence interval 95%, dan (3) Mengeksekusi logrank_test untuk menguji signifikansi perbedaannya!",
             "Skrip Python:\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\nfrom lifelines.statistics import logrank_test\n# 1. Fitting Kaplan-Meier\nkmf_mono = KaplanMeierFitter()\nkmf_micro = KaplanMeierFitter()\n# Kelompok Monolith\nmask_mono = (df_sre['arch'] == 'v1_Monolith')\nkmf_mono.fit(df_sre[mask_mono]['runtime_hours'], df_sre[mask_mono]['failed'], label='v1 Monolith')\n# Kelompok Microservices\nmask_micro = (df_sre['arch'] == 'v2_Microservice')\nkmf_micro.fit(df_sre[mask_micro]['runtime_hours'], df_sre[mask_micro]['failed'], label='v2 Microservice')\n# 2. Visualisasi Kurva Keandalan\nplt.figure(figsize=(9, 5))\nax = kmf_mono.plot_survival_function(ci_show=True, color='#E53E3E')\nkmf_micro.plot_survival_function(ax=ax, ci_show=True, color='#3182CE')\nplt.title('Kurva Keandalan Sistem: Kaplan-Meier Survival Curve', fontweight='bold')\nplt.xlabel('Waktu Operasional Uptime (Jam)'); plt.ylabel('Probabilitas Keandalan S(t)')\nplt.grid(True, linestyle='--'); plt.show()\n# 3. Uji Log-Rank\nres = logrank_test(df_sre[mask_mono]['runtime_hours'], df_sre[mask_micro]['runtime_hours'],\n                   df_sre[mask_mono]['failed'], df_sre[mask_micro]['failed'])\nprint(f'Log-Rank Test: Chi2 = {res.test_statistic:.4f}, p-value = {res.p_value:.4e}')",
             "Bobot 100: Fitting KaplanMeierFitter untuk 2 kelompok tepat (35%), visualisasi kurva survival dengan CI rapi (35%), eksekusi logrank_test tepat (30%).")
        ]
    )

    # Modul 23: Pemodelan Retensi & Churn Pengguna (Cox Hazard)
    add_module(
        23, "Pemodelan Retensi & Churn Pengguna (Cox Hazard)", "Buku 2",
        [
            ("Model Regresi Bahaya Proporsional Cox (Cox Proportional Hazards Model) dirumuskan dengan persamaan h(t | X) = h_0(t) * exp(beta_1*X_1 + ... + beta_k*X_k), di mana h_0(t) merepresentasikan:",
             {"A": "Fungsi bahaya dasar (Baseline Hazard Function) pada saat semua kovariat X = 0", "B": "Nilai rata-rata waktu churn", "C": "Koefisien determinasi R²", "D": "Tingkat akurasi klasifikasi", "E": "Biaya langganan SaaS"}, "A",
             "Baseline Hazard h_0(t) adalah laju bahaya dasar fungsi waktu murni ketika seluruh nilai kovariat prediktor X bernilai nol."),
            ("Dalam model Cox Proportional Hazards, nilai Hazard Ratio (HR) untuk sebuah variabel prediktor dihitung dengan rumus:",
             {"A": "HR = beta", "B": "HR = exp(beta)", "C": "HR = 1 / beta", "D": "HR = ln(beta)", "E": "HR = beta²"}, "B",
             "Hazard Ratio (HR) adalah rasio laju bahaya eksponensial dari koefisien: HR = exp(beta)."),
            ("Jika variabel 'tiket_keluhan_belum_tuntas' memiliki koefisien Cox beta = +0.6931 (sehingga HR = exp(0.6931) = 2.00), interpretasi yang tepat adalah:",
             {"A": "Setiap penambahan 1 tiket keluhan melipatgandakan laju risiko churn pengguna sebesar 2 kali lipat (kenaikan risiko +100%)", "B": "Tiket keluhan menurunkan risiko churn", "C": "Pengguna pasti berhenti berlangganan dalam 2 hari", "D": "Model tidak valid", "E": "Tiket keluhan tidak berpengaruh"}, "A",
             "HR = 2.00 (> 1.0) menunjukkan faktor risiko: setiap kenaikan 1 satuan tiket keluhan yang tidak terselesaikan menggandakan laju hazard churn pengguna sebesar 2 kali lipat pada setiap titik waktu."),
            ("Asumsi fundamental 'Proportional Hazards' (Bahaya Proporsional) pada model Cox menyatakan bahwa:",
             {"A": "Laju hazard selalu bernilai konstan sepanjang waktu", "B": "Rasio hazard antar dua individu dengan kovariat berbeda bersifat konstan dan tidak berubah seiring berjalannya waktu t", "C": "Semua pengguna memiliki waktu churn yang sama", "D": "Data harus berdistribusi normal", "E": "Tidak boleh ada data tersensor"}, "B",
             "Asumsi Proportional Hazards menetapkan bahwa rasio laju bahaya HR antar individu bersifat invarian terhadap waktu (garis log-hazard paralel sepanjang waktu t).")
        ],
        [
            ("Jika koefisien Cox untuk fitur 'diskon_tahunan' adalah beta = -0.5108, berapakah nilai Hazard Ratio (HR)-nya?",
             "HR = 0.60 (atau exp(-0.5108))", "HR = exp(-0.5108) = 0.60. Artinya diskon tahunan bersifat protektif dan menurunkan risiko churn sebesar 40% (1 - 0.60)."),
            ("Apakah arti nilai Hazard Ratio HR = 1.0 pada model regresi Cox?",
             "Kovariat tidak memiliki pengaruh terhadap laju risiko churn (Netral / Tidak Berpengaruh)", "Jika HR = 1.0 (beta = 0), variabel prediktor tidak menaikkan maupun menurunkan laju bahaya terjadinya peristiwa."),
            ("Sebutkan nama kelas pemodelan dalam pustaka Lifelines Python yang digunakan untuk melatih regresi Cox Proportional Hazards!",
             "lifelines.CoxPHFitter", "CoxPHFitter adalah kelas estimator regresi Cox semi-parametrik dalam pustaka Lifelines."),
            ("Metode uji statistik apakah yang digunakan untuk memverifikasi validitas asumsi Proportional Hazards pada model Cox?",
             "Uji Residu Schoenfeld (Schoenfeld Residuals Test / proportional_hazard_test)", "Uji residu Schoenfeld memeriksa apakah korelasi residu terhadap waktu bernilai nol (tidak bergantung pada waktu).")
        ],
        [
            ("Jelaskan mengapa model Regresi Bahaya Proporsional Cox (Cox Proportional Hazards) digolongkan sebagai model 'Semi-Parametrik' dan jelaskan keunggulannya dibandingkan model Regresi Logistik biasa dalam memprediksi churn pengguna SaaS!",
             "1. Mengapa Semi-Parametrik: Karena model Cox tidak membuat asumsi parametrik apapun mengenai bentuk distribusi fungsi bahaya dasar h_0(t) (komponen non-parametrik bebas distribusi), namun memodelkan pengaruh kovariat prediktor X secara parametrik linier eksponensial exp(beta * X). Model dioptimasi menggunakan Partial Likelihood Cox tanpa perlu mengestimasi h_0(t).\n2. Keunggulan vs Regresi Logistik:\n- Penanganan Dimensi Waktu: Regresi Logistik hanya menjawab 'Apakah user churn atau tidak' pada jendela waktu statis (misal 30 hari) dan mengabaikan kapan churn terjadi. Model Cox menjawab 'Kapan user churn' dan memodelkan dinamika laju risiko di sepanjang kurva waktu kontinu.\n- Pemanfaatan Data Tersensor: Regresi Logistik membuang atau mendistorsi data pengguna aktif yang belum churn. Model Cox memperlakukan pengguna aktif sebagai right-censored data yang informatif, menghasilkan estimasi retensi masa depan yang jauh lebih akurat.",
             "Bobot 100: Definisi semi-parametrik & partial likelihood tepat (40%), keunggulan dimensi waktu & penanganan data tersensor vs regresi logistik (60%)."),
            ("Sebuah perusahaan SaaS B2B memodelkan churn 500 pelanggan menggunakan CoxPHFitter. Hasil estimasi parameter menunjukkan:\n- Paket Enterprise (vs Basic): beta = -1.20, p = 0.001, HR = 0.301\n- Hari Aktif Bulanan: beta = -0.08, p = 0.0002, HR = 0.923\n- Tiket Keluhan Unresolved: beta = +0.45, p = 0.0005, HR = 1.568\n(a) Jelaskan interpretasi mendalam dari nilai Hazard Ratio (HR) ketiga variabel tersebut! (b) Rancang strategi retensi pengguna (Customer Success Strategy) berbasis data hasil model tersebut!",
             "(a) Interpretasi Hazard Ratio:\n1. Paket Enterprise (HR = 0.301): Pelanggan Enterprise memiliki laju risiko churn 69.9% lebih rendah (1 - 0.301) dibandingkan pelanggan paket Basic. Paket Enterprise bersifat protektif tinggi.\n2. Hari Aktif Bulanan (HR = 0.923): Setiap tambahan 1 hari aktif per bulan menurunkan laju risiko churn sebesar 7.7% (1 - 0.923).\n3. Tiket Keluhan Unresolved (HR = 1.568): Setiap penambahan 1 tiket keluhan yang tidak selesai meningkatkan laju risiko churn sebesar 56.8% (HR = 1.568 > 1.0).\n(b) Strategi Retensi Customer Success:\n1. Up-selling & Onboarding: Dorong pelanggan Basic untuk upgrade ke paket Enterprise dengan pelatihan fitur berkala.\n2. In-App Engagement Triggers: Bangun sistem peringatan dini (Early Warning Alert) jika hari aktif pengguna turun di bawah 10 hari/bulan untuk memicu intervensi tim support.\n3. SLA Resolusi Tiket Kritis: Prioritaskan penyelesaian tiket keluhan dalam 24 jam karena setiap tiket yang menggantung melipatgandakan risiko churn secara drastis.",
             "Bobot 100: Interpretasi HR 3 variabel tepat (50%), perancangan 3 strategi Customer Success berbasis data empiris (50%)."),
            ("Jelaskan asumsi 'Proportional Hazards' pada model Cox, apa dampak jika asumsi ini dilanggar oleh salah satu variabel prediktor, dan sebutkan 2 pendekatan komputasi untuk mengatasinya!",
             "Asumsi Proportional Hazards (PH): Mensyaratkan bahwa rasio bahaya (Hazard Ratio) antar level kovariat bersifat konstan sepanjang waktu pemantauan. Residu Schoenfeld tidak boleh berkorelasi dengan waktu (p > 0.05).\nDampak Pelanggaran: Jika asumsi dilanggar (misal efek promo diskon hanya berpengaruh kuat di bulan pertama, lalu memudar di bulan ke-6), nilai beta rata-rata model Cox menjadi bias dan menyesatkan karena efek variabel berubah seiring waktu.\n2 Solusi Komputasi:\n1. Stratified Cox Model: Variabel yang melanggar asumsi dijadikan variabel stratifikasi (strata). Model akan mengizinkan baseline hazard h_0(t) berbeda untuk tiap strata tanpa mengasumsikan proporsionalitas.\n2. Time-Varying Covariates / Time-Dependent Coefficients: Memodelkan koefisien sebagai fungsi interaksi eksplisit dengan waktu: beta(t) = beta_0 + beta_1 * ln(t).",
             "Bobot 100: Penjelasan asumsi PH & residu Schoenfeld (40%), dampak pelanggaran asumsi (30%), 2 teknik solusi Stratified Cox & Time-Varying Covariates (30%)."),
            ("Tuliskan skrip Python lengkap menggunakan lifelines untuk: (1) Melatih CoxPHFitter pada dataset retensi pengguna, (2) Menampilkan ringkasan model (summary) beserta nilai Hazard Ratio dan p-value, (3) Memeriksa asumsi Proportional Hazards dengan check_assumptions, dan (4) Memplot koefisien log-hazard ratio!",
             "Skrip Python:\nimport matplotlib.pyplot as plt\nfrom lifelines import CoxPHFitter\n# 1. Training Model Cox\ncph = CoxPHFitter()\ncph.fit(df_retention, duration_col='tenure_months', event_col='churn_event')\n# 2. Ringkasan Parameter & Hazard Ratio\nprint('=== RINGKASAN MODEL REGRESI COX PROPORTIONAL HAZARDS ===')\ndisplay(cph.summary[['coef', 'exp(coef)', 'se(coef)', 'p', 'exp(coef) lower 95%', 'exp(coef) upper 95%']])\n# 3. Uji Asumsi Proportional Hazards\nprint('\\n=== Uji Asumsi Proportional Hazards (Schoenfeld Residu) ===')\ncph.check_assumptions(df_retention, p_value_threshold=0.05, show_plots=False)\n# 4. Visualisasi Forest Plot Koefisien\nplt.figure(figsize=(8, 5))\ncph.plot()\nplt.title('Plot Koefisien Log-Hazard Ratio Model Cox', fontweight='bold')\nplt.show()",
             "Bobot 100: Inisialisasi & fitting CoxPHFitter tepat (35%), ekstraksi ringkasan summary tepat (30%), check_assumptions & cph.plot() tepat (35%).")
        ]
    )

    # Modul 24: Studi Kasus 4: Usabilitas SIM Kampus
    add_module(
        24, "Studi Kasus 4: Usabilitas SIM Kampus", "Buku 2",
        [
            ("Dalam studi kasus komprehensif evaluasi redesain Sistem Informasi Akademik (SIM Kampus), integrasi metodologi statistik yang diterapkan mencakup:",
             {"A": "Kuesioner SUS 10 butir, Uji Reliabilitas Cronbach's Alpha, Independent t-Test, dan Two-Way ANOVA Pengguna x Versi", "B": "K-Means Clustering semata", "C": "Dekomposisi PCA tanpa validasi", "D": "Regresi Logistik biner murni", "E": "Market Basket Apriori"}, "A",
             "Evaluasi usabilitas SIM kampus mengintegrasikan pengukuran instrumen SUS, pengujian konsistensi psikometrik Cronbach's Alpha, serta uji inferensial komparasi t-Test dan Two-Way ANOVA."),
            ("Jika hasil uji Independent Two-Sample t-Test antara skor SUS SIM Lama vs SIM Redesain menghasilkan t = 0.1672 dan p-value = 0.8674 (p > 0.05), kesimpulan manakah yang benar?",
             {"A": "SIM Redesain terbukti secara signifikan lebih baik daripada SIM Lama", "B": "Tidak terdapat perbedaan usabilitas yang signifikan secara statistik antara SIM Lama dan SIM Redesain (Redesain gagal meningkatkan usabilitas)", "C": "SIM Lama harus segera dimatikan", "D": "Skor SUS tidak valid", "E": "Data berdistribusi binomial"}, "B",
             "Karena p-value = 0.8674 > 0.05, gagal tolak H0. Secara statistik tidak ada bukti bahwa versi redesain memberikan perbaikan skor usabilitas nyata bagi pengguna kampus."),
            ("Pentingnya menganalisis perbedaan skor usabilitas per kelompok pengguna (Mahasiswa, Dosen, Tenaga Kependidikan) pada evaluasi SIM Kampus adalah:",
             {"A": "Agar kuesioner terlihat lebih panjang", "B": "Karena tiap kelompok pengguna memiliki alur kerja (workflow) dan kebutuhan fungsional antarmuka yang sangat berbeda, sehingga skor agregat dapat menyamarkan ketidakpuasan kelompok tertentu", "C": "Untuk mengurangi jumlah sampel penelitian", "D": "Untuk mempercepat eksekusi database", "E": "Agar nilai alpha menjadi 1.0"}, "B",
             "Mahasiswa berfokus pada pengisian KRS dan melihat nilai; Dosen berfokus pada input nilai dan bimbingan; Tendik berfokus pada validasi kurikulum. Agregasi global dapat menutupi masalah krusial pada alur kerja Dosen/Tendik."),
            ("Jika nilai koefisien Cronbach's Alpha dari instrumen kuesioner survei usabilitas SIM Kampus adalah alpha = 0.948, maka status reliabilitas instrumen tersebut adalah:",
             {"A": "Tidak Reliabel (Gagal Uji)", "B": "Cukup / Marginal", "C": "Sangat Reliabel / Ekselen (Excellent Internal Consistency)", "D": "Mengalami Error Pembagian Nol", "E": "Hanya valid untuk 1 responden"}, "C",
             "Nilai alpha >= 0.90 dikategorikan sebagai instrumen dengan reliabilitas internal sangat tinggi (Excellent).")
        ],
        [
            ("Berapakah nilai standar industri (benchmark) skor SUS rata-rata yang dijadikan tolok ukur minimal kelayakan sistem informasi?",
             "Skor SUS = 68.0", "Skor 68.0 adalah rata-rata standar industri global kelayakan usabilitas sistem."),
            ("Uji statistik inferensial apakah yang digunakan untuk membandingkan skor SUS antara dua versi SIM (Versi Lama vs Versi Baru) pada dua kelompok pengguna independen?",
             "Independent Samples t-Test (Uji-t Dua Sampel Independen)", "Uji-t dua sampel independen membandingkan rata-rata dua kelompok subjek yang berbeda."),
            ("Jika hasil pengujian Two-Way ANOVA menunjukkan Efek Interaksi signifikan antara Kelompok Pengguna dan Versi SIM, apakah artinya bagi tim pengembang?",
             "Artinya dampak redesain sistem tidak sama pada setiap kelompok pengguna (misal: sukses meningkatkan kepuasan Mahasiswa, tetapi justru mempersulit Dosen)", "Efek interaksi menandakan respons yang berbeda dari masing-masing tipe pengguna terhadap perubahan sistem."),
            ("Sebutkan formula konversi butir negatif (butir bernomor genap) pada kuesioner System Usability Scale (SUS)!",
             "Skor Termodifikasi = 5 - Skor Jawaban", "Formula butir genap SUS membalik skala Likert: 5 - Skor.")
        ],
        [
            ("Berdasarkan studi kasus evaluasi redesain SIM Kampus: Rata-rata skor SUS SIM Lama adalah 73.36 dan SIM Redesain adalah 73.63, dengan hasil uji Independent t-Test menunjukkan t = 0.1672 dan p-value = 0.8674. (a) Jelaskan mengapa secara statistik proyek redesain tersebut dinyatakan TIDAK EFEKTIF meskipun skor rata-ratanya tampak naik sedikit! (b) Jika Anda adalah Chief Technology Officer (CTO) kampus, langkah audit data dan rekayasa apa yang akan Anda instruksikan kepada tim pengembang?",
             "(a) Evaluasi Kegagalan Redesain: Kenaikan skor sebesar 0.27 poin (dari 73.36 ke 73.63) adalah sangat kecil dan secara statistik terbukti murni fluktuasi acak (p-value = 0.8674 jauh di atas ambang batas 0.05). Tim produk tidak boleh mengklaim redesain berhasil karena secara ilmiah tidak ada bukti perbaikan usabilitas nyata yang dirasakan pengguna.\n(b) Instruksi Audit CTO:\n1. Analisis Strata Pengguna (Two-Way ANOVA): Bongkar skor agregat menjadi 3 kelompok terpisah (Mahasiswa, Dosen, Tendik). Cari tahu apakah kenaikan skor di kalangan Mahasiswa mengaburkan penurunan drastis skor di kalangan Dosen akibat alur input nilai baru yang rumit.\n2. Audit Butir Diagnostik SUS: Periksa butir spesifik SUS dengan skor terburuk (misal Q4 'Saya merasa membutuhkan bantuan teknis' atau Q10 'Saya perlu belajar banyak hal sebelum menguasai sistem').\n3. Usability Testing Kualitatif & Task Success Rate: Lakukan uji lab langsung pada 10 dosen dan 10 tendik dengan merekam Task Completion Time dan Error Rate pada fitur-fitur krusial.",
             "Bobot 100: Analisis ketidaksignifikanan statistik t-test tepat (40%), rencana audit 3 langkah CTO komprehensif dan aplikatif (60%)."),
            ("Jelaskan rancangan instrumen kuesioner dan metodologi pengujian validitas-reliabilitas yang benar sebelum kuesioner evaluasi sistem informasi disebarkan ke 500 civitas akademika kampus!",
             "Rancangan Metodologis:\n1. Konstruk Teoretis: Kuesioner dirancang mengadopsi kerangka SUS 10 butir dan TAM (Perceived Usefulness & Perceived Ease of Use) dengan skala Likert 1-5.\n2. Uji Coba Terbatas (Pilot Testing): Sebar kuesioner awal ke sampel pilot n = 30 responden yang representatif.\n3. Uji Validitas Butir: Hitung Corrected Item-Total Correlation Pearson (r). Butir dinyatakan valid jika r >= 0.30 (atau r-hitung > r-tabel df=28). Butir dengan r < 0.30 direvisi atau dieliminasi.\n4. Uji Reliabilitas Konsistensi Internal: Hitung koefisien Cronbach's Alpha. Instrumen dinyatakan reliabel jika alpha >= 0.70.\n5. Pemeriksaan Alpha if Item Deleted: Pastikan tidak ada butir yang jika dibuang akan menaikkan nilai reliabilitas secara signifikan.\n6. Pengumpulan Data Massal: Setelah instrumen terbukti valid dan reliabel pada uji pilot, kuesioner baru disebarkan secara resmi ke 500 responden populasi kampus.",
             "Bobot 100: Tahapan pilot testing n=30 tepat (25%), kriteria validitas r >= 0.30 tepat (25%), kriteria reliabilitas alpha >= 0.70 tepat (25%), prosedur rilis kuesioner massal tepat (25%)."),
            ("Jelaskan bagaimana analisis Two-Way ANOVA (Faktor 1: Versi SIM Lama vs Baru; Faktor 2: Kelompok Pengguna Mahasiswa vs Dosen vs Tendik) mampu mengungkap 'Hidden Friction' (Friksi Tersembunyi) yang tidak terlihat pada uji t-test agregat!",
             "Mekanisme Pengungkapan Hidden Friction:\n- Uji t-test agregat menggabungkan semua data menjadi satu kesatuan rata-rata. Jika 80% sampel adalah Mahasiswa yang menyukai UI baru (+5 poin), tetapi 10% Dosen (-10 poin) dan 10% Tendik (-10 poin) sangat frustrasi dengan UI baru, rata-rata agregat tetap terlihat positif/netral.\n- Two-Way ANOVA memisahkan variabilitas menjadi Main Effect Versi, Main Effect Kelompok, dan Efek Interaksi (Versi x Kelompok).\n- Uji Interaksi akan mendeteksi apakah kurva respons kepuasan berlawanan arah antar kelompok pengguna (Interaction Plot saling bersilangan). Hal ini membongkar friksi tersembunyi bahwa sistem baru mungkin mempermudah mahasiswa yang transaksinya sederhana, namun merusak produktivitas dosen dan tendik yang mengelola alur kerja akademik kompleks.",
             "Bobot 100: Analisis kelemahan agregasi data t-test (40%), mekanisme dekomposisi varians Two-Way ANOVA (35%), deteksi friksi tersembunyi via interaction plot (25%)."),
            ("Tuliskan pipeline skrip Python lengkap untuk menganalisis dataset studi kasus SIM Kampus: (1) Menghitung skor SUS per responden, (2) Uji normalitas Shapiro-Wilk dan uji beda Independent t-Test antara SIM Lama dan Baru, (3) Model Two-Way ANOVA 'sus_score ~ C(system_version) * C(user_group)', dan (4) Visualisasi boxplot perbandingan antarmuka per kelompok!",
             "Skrip Python:\nimport pandas as pd, scipy.stats as stats, statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nimport matplotlib.pyplot as plt, seaborn as sns\n# 1. Independent t-Test\nscore_old = df_sim[df_sim['version']=='Old']['sus_score']\nscore_new = df_sim[df_sim['version']=='New']['sus_score']\nt_stat, p_val = stats.ttest_ind(score_old, score_new)\nprint(f'Independent t-Test: t = {t_stat:.4f}, p-value = {p_val:.4e}')\n# 2. Two-Way ANOVA Faktorial\nmodel = ols('sus_score ~ C(version) * C(user_group)', data=df_sim).fit()\nanova_res = sm.stats.anova_lm(model, typ=2)\nprint('\\n=== Tabel Two-Way ANOVA ===')\ndisplay(anova_res)\n# 3. Visualisasi Boxplot\nplt.figure(figsize=(9, 5))\nsns.boxplot(data=df_sim, x='user_group', y='sus_score', hue='version', palette=['#718096', '#3182CE'])\nplt.axhline(68.0, color='red', linestyle='--', label='Benchmark Industri (68.0)')\nplt.title('Perbandingan Skor Usabilitas SUS: Versi Lama vs Baru per Kelompok Pengguna', fontweight='bold')\nplt.ylabel('Skor SUS'); plt.legend(); plt.show()",
             "Bobot 100: Eksekusi t-test tepat (30%), model Two-Way ANOVA tepat (35%), visualisasi boxplot komparatif dengan garis benchmark 68.0 rapi (35%).")
        ]
    )

    # Modul 25: Studi Kasus 5: Game Edukasi Metode MDA
    add_module(
        25, "Studi Kasus 5: Game Edukasi Metode MDA", "Buku 2",
        [
            ("Tiga pilar hierarki dalam kerangka perancangan dan analisis game MDA Framework menurut Hunicke, LeBlanc, dan Zubek (2004) adalah:",
             {"A": "Memory, Disk, Allocation", "B": "Mechanics, Dynamics, Aesthetics", "C": "Model, Design, Architecture", "D": "Marketing, Delivery, Analytics", "E": "Metrics, Data, Assessment"}, "B",
             "MDA Framework membagi game menjadi 3 pilar: Mechanics (aturan formal & algoritma game), Dynamics (perilaku interaksi runtime pemain), dan Aesthetics (respons emosional & pengalaman bermain)."),
            ("Formula Normalized Gain (N-Gain / g) menurut Richard Hake (1998) yang digunakan untuk mengukur peningkatan pemahaman siswa sebelum dan sesudah memainkan game edukasi adalah:",
             {"A": "g = Posttest - Pretest", "B": "g = (Posttest - Pretest) / (Skor Maksimum Ideal - Pretest)", "C": "g = Posttest / Pretest", "D": "g = (Posttest + Pretest) / 2", "E": "g = Posttest / Skor Maksimum"}, "B",
             "Formula N-Gain Hake mengukur rasio peningkatan aktual terhadap potensi peningkatan maksimum yang bisa dicapai: g = (Post - Pre) / (Max_Score - Pre)."),
            ("Berdasarkan kriteria interpretasi Richard Hake, efektivitas peningkatan pemahaman siswa dikategorikan 'Tinggi' (High Gain) jika nilai N-Gain rata-rata memenuhi:",
             {"A": "g < 0.30", "B": "0.30 <= g < 0.70", "C": "g >= 0.70 (atau g >= 70%)", "D": "g = 0", "E": "g bernilai negatif"}, "C",
             "Kategori N-Gain Hake: g >= 0.70 (Tinggi / Efektivitas Kuat), 0.30 <= g < 0.70 (Sedang), g < 0.30 (Rendah)."),
            ("Uji statistik inferensial parametrik yang digunakan untuk menguji apakah perbedaan skor rata-rata Pre-Test dan Post-Test siswa signifikan secara statistik adalah:",
             {"A": "Paired Samples t-Test (Uji-t Berpasangan)", "B": "Independent t-Test", "C": "One-Way ANOVA", "D": "Uji Chi-Square Goodness of Fit", "E": "Uji Mann-Whitney U"}, "A",
             "Karena setiap siswa diukur dua kali pada variabel yang sama (sebelum bermain dan sesudah bermain), data bersifat berpasangan sehingga diuji menggunakan Paired Samples t-Test.")
        ],
        [
            ("Jika seorang siswa memperoleh skor Pre-Test = 40 dan skor Post-Test = 85 pada skala tes maksimum 100, berapakah nilai Normalized Gain (N-Gain) siswa tersebut?",
             "N-Gain = 0.75 (Kategori Tinggi)", "g = (85 - 40) / (100 - 40) = 45 / 60 = 0.75 (75.0%)."),
            ("Pilar MDA manakah yang merepresentasikan 'respons emosional, sensasi estetika, dan kesenangan (fun) yang dirasakan oleh pemain saat bermain game'?",
             "Aesthetics (Estetika Pengalaman)", "Aesthetics mencakup sensasi kesenangan, tantangan (challenge), narasi (narrative), dan ekspresi emosional pemain."),
            ("Tuliskan kepanjangan dari 3 huruf akronim kerangka game MDA!",
             "Mechanics, Dynamics, Aesthetics", "MDA adalah singkatan dari Mechanics, Dynamics, dan Aesthetics."),
            ("Metrik Effect Size apakah yang digunakan untuk mengukur besarnya dampak intervensi game edukasi terhadap peningkatan hasil belajar?",
             "Cohen's d (Effect Size)", "Cohen's d mengukur magnitudo perbedaan skor rata-rata terstandarisasi sebelum dan sesudah intervensi game.")
        ],
        [
            ("Jelaskan konsep kerangka perancangan game MDA Framework (Hunicke et al., 2004) dari dua perspektif yang berlawanan: Perspektif Desainer Game (Mechanics -> Dynamics -> Aesthetics) vs Perspektif Pemain (Aesthetics -> Dynamics -> Mechanics)!",
             "1. Perspektif Desainer Game (Top-Down Creation):\n- Mechanics: Desainer menulis aturan formal, algoritma skor, fisika game, dan mekanisme kontrol tombol.\n- Dynamics: Saat game dijalankan (runtime), mekanisme berinteraksi dengan input pemain menciptakan dinamika sistem (strategi pemain, ritme permainan, pola pergerakan musuh).\n- Aesthetics: Dinamika tersebut menghasilkan pengalaman emosional dan estetika kesenangan (tantangan, rasa ingin tahu, kepuasan belajar).\n2. Perspektif Pemain (Bottom-Up Experience):\n- Aesthetics: Pemain pertama kali merasakan estetika dan atmosfer visual/emosional (apakah game ini seru, menyenangkan, menegangkan).\n- Dynamics: Pemain mulai mempelajari dinamika interaksi (bagaimana cara menghindari rintangan dan mengoptimalkan taktik).\n- Mechanics: Pemain akhirnya menyadari aturan dasar, mekanisme poin, dan keterbatasan matematis game.\nImplikasi Game Edukasi: Desainer harus merancang Mechanics pembelajaran yang terintegrasi halus agar Dynamics permainan menghasilkan Aesthetics belajar yang menyenangkan tanpa terasa seperti ujian konvensional.",
             "Bobot 100: Penjelasan perspektif Desainer tepat (40%), penjelasan perspektif Pemain tepat (40%), integrasi dalam game edukasi tepat (20%)."),
            ("Sebuah studi eksperimen menguji efektivitas game edukasi logika algoritma berbasis MDA pada 40 siswa SMA. Hasil pengujian menunjukkan:\n- Rata-rata Skor Pre-Test: 48.5 (Standar Deviasi: 12.0)\n- Rata-rata Skor Post-Test: 89.5 (Standar Deviasi: 8.5)\n- Skor Maksimum Tes Ideal: 100.0\n- Rata-rata Selisih Skor (d_bar) = 41.0 dengan Standar Deviasi Selisih (s_d) = 9.2\n(a) Hitunglah nilai rata-rata Normalized Gain (N-Gain Hake) dan tentukan kategorinya! (b) Hitunglah nilai t-hitung Paired t-Test dan Cohen's d Effect Size! (c) Berikan kesimpulan pedagogis dan rekayasa perangkat lunak terhadap efektivitas game edukasi tersebut!",
             "(a) Perhitungan N-Gain Hake:\ng = (Post_bar - Pre_bar) / (Max_Score - Pre_bar) = (89.5 - 48.5) / (100.0 - 48.5) = 41.0 / 51.5 = 0.7961 (79.61%).\nKategori: N-Gain g = 0.80 >= 0.70 masuk ke dalam Kategori TINGGI (High Gain).\n(b) Perhitungan Uji Inferensial & Effect Size:\n- Standar Error SE = s_d / sqrt(n) = 9.2 / sqrt(40) = 9.2 / 6.3246 = 1.4546.\n- Nilai t-hitung = d_bar / SE = 41.0 / 1.4546 = +28.187 (df = 39, p-value < 0.0001).\n- Cohen's d = d_bar / s_d = 41.0 / 9.2 = 4.456 (Very Large Effect Size).\n(c) Kesimpulan: Game edukasi terbukti secara statistik sangat signifikan (t = 28.19, p < 0.0001) dan memiliki dampak efektivitas pembelajaran yang luar biasa besar (Cohen d = 4.46, N-Gain 79.61%). Game edukasi berbasis MDA ini sangat layak diimplementasikan sebagai media pembelajaran kurikulum resmi.",
             "Bobot 100: Perhitungan N-Gain dan penentuan kategori tepat (35%), perhitungan t-hitung dan Cohen's d tepat (35%), penarikan kesimpulan ilmiah dan praktis tepat (30%)."),
            ("Jelaskan mengapa evaluasi peningkatan belajar siswa WAJIB menggunakan metrik Normalized Gain (N-Gain Hake) dan TIDAK BOLEH hanya mengandalkan selisih skor mentah (Absolute Gain = Posttest - Pretest)!",
             "Kelemahan Absolute Gain (Post - Pre):\n- Mengabaikan 'Headroom Effect' (Batas Atas Potensi). Siswa A yang naik dari skor 20 ke 50 memiliki Absolute Gain = +30. Siswa B yang naik dari skor 70 ke 95 memiliki Absolute Gain = +25. Jika memakai selisih mentah, Siswa A tampak 'lebih berprestasi' dibanding Siswa B.\n- Padahal Siswa B berhasil meraih 95 dari batas maksimal 100 (hampir sempurna, potensi sisa 30 diraih 25 = N-Gain 83.3%), sedangkan Siswa A hanya meraih 30 dari potensi sisa 80 (N-Gain 37.5%).\nKeunggulan Normalized Gain:\n- N-Gain menormalkan peningkatan terhadap kapasitas ruang perbaikan yang tersedia (Max - Pre), sehingga adil bagi siswa yang memiliki nilai awal pretest tinggi maupun rendah, dan mencegah bias ceiling effect dalam evaluasi efektivitas media pembelajaran.",
             "Bobot 100: Analisis kelemahan Absolute Gain & Headroom Effect (45%), keunggulan matematis N-Gain Hake (40%), contoh kasus perbandingan siswa A vs B (15%)."),
            ("Tuliskan skrip Python lengkap untuk menganalisis data evaluasi game edukasi: (1) Menghitung kolom 'n_gain' per siswa dengan rumus Hake, (2) Melakukan Paired Samples t-Test antara Pre-Test dan Post-Test, (3) Menghitung korelasi Pearson antara kepuasan bermain (MDA rating) dengan N-Gain, dan (4) Memvisualisasikan KDE distribusi Pre-Test vs Post-Test!",
             "Skrip Python:\nimport pandas as pd, numpy as np, scipy.stats as stats\nimport matplotlib.pyplot as plt, seaborn as sns\n# 1. Perhitungan N-Gain Hake (Max Score = 100)\ndf_game['n_gain'] = (df_game['posttest'] - df_game['pretest']) / (100.0 - df_game['pretest'])\nprint(f'Rata-rata N-Gain: {df_game[\"n_gain\"].mean():.4f} (Kategori: {\"Tinggi\" if df_game[\"n_gain\"].mean()>=0.7 else \"Sedang\"})')\n# 2. Paired t-Test\nt_stat, p_val = stats.ttest_rel(df_game['posttest'], df_game['pretest'])\nprint(f'Paired t-Test: t = {t_stat:.4f}, p-value = {p_val:.4e}')\n# 3. Korelasi MDA Rating vs N-Gain\nr_val, p_corr = stats.pearsonr(df_game['mda_satisfaction'], df_game['n_gain'])\nprint(f'Korelasi Kepuasan MDA vs N-Gain: r = {r_val:.4f} (p = {p_corr:.4e})')\n# 4. Visualisasi Distribusi Pre vs Post\nplt.figure(figsize=(8, 5))\nsns.kdeplot(df_game['pretest'], label='Pre-Test (Sebelum Bermain)', color='#E53E3E', fill=True)\nsns.kdeplot(df_game['posttest'], label='Post-Test (Sesudah Bermain)', color='#3182CE', fill=True)\nplt.title('Distribusi Peningkatan Pemahaman Siswa: Pre-Test vs Post-Test', fontweight='bold')\nplt.xlabel('Skor Tes (0 - 100)'); plt.legend(); plt.show()",
             "Bobot 100: Perhitungan vektor N-Gain tepat (30%), eksekusi Paired t-Test dan korelasi Pearson tepat (35%), visualisasi KDE plot rapi (35%).")
        ]
    )

print("modules_part5.py ready...")
