# Modul 15 - 19

def load_part4(add_module):
    # Modul 15: Metrik SDLC, Defect Density & Sampling
    add_module(
        15, "Metrik SDLC, Defect Density & Sampling", "Buku 2",
        [
            ("Metrik kualitas perangkat lunak 'Defect Density' dihitung dengan membagi jumlah cacat bug yang ditemukan dengan:",
             {"A": "Jumlah developer dalam tim", "B": "Ukuran basis kode (KLOC / Kilo Lines of Code)", "C": "Lama durasi sprint dalam hari", "D": "Total biaya proyek", "E": "Jumlah commit harian"}, "B",
             "Defect Density = Total Defect Count / KLOC. Mengukur kepadatan cacat bug per seribu baris kode program untuk membandingkan kualitas antar modul software."),
            ("Rumus Slovin n = N / (1 + N * e²) digunakan dalam metodologi sampling riset software engineering untuk menentukan:",
             {"A": "Jumlah baris kode yang harus direfaktor", "B": "Ukuran sampel minimum n dari populasi N dengan margin of error toleransi e", "C": "Tingkat kompleksitas siklomatis", "D": "Lead time pengiriman fitur", "E": "Waktu pemulihan layanan MTTR"}, "B",
             "Rumus Slovin adalah formula praktis penentuan ukuran sampel representatif dari populasi terhingga N dengan tingkat presisi kelonggaran ketidaktelitian e."),
            ("Metrik kompleksitas kode program yang menghitung jumlah jalur eksekusi independen linier melalui graf alir kendali (Control Flow Graph) disebut:",
             {"A": "Lines of Code (LOC)", "B": "Cyclomatic Complexity (McCabe)", "C": "Halstead Volume", "D": "Code Coverage Percentage", "E": "Technical Debt Ratio"}, "B",
             "Cyclomatic Complexity M = E - N + 2P mengukur kompleksitas struktural kode program berdasarkan jumlah titik keputusan percabangan (if/else/loops)."),
            ("Berikut ini yang BUKAN merupakan salah satu dari 4 Metrik Kunci DORA (DevOps Research and Assessment) adalah:",
             {"A": "Deployment Frequency", "B": "Lead Time for Changes", "C": "Change Failure Rate", "D": "Lines of Code per Developer", "E": "Time to Restore Service (MTTR)"}, "D",
             "4 Metrik DORA adalah: Deployment Frequency, Lead Time for Changes, Change Failure Rate, dan Time to Restore Service. 'Lines of Code per Developer' adalah metrik vanity yang usang.")
        ],
        [
            ("Jika sebuah modul microservice memiliki 25.000 baris kode (25 KLOC) dan ditemukan 50 bug selama fase QA, berapakah nilai Defect Density modul tersebut?",
             "Defect Density = 2.0 Defect / KLOC", "Defect Density = 50 Defect / 25 KLOC = 2.0 Defect per KLOC."),
            ("Sebuah populasi pengguna aplikasi memiliki N = 10.000 pengguna. Dengan margin of error toleransi e = 5% (0.05), berapakah ukuran sampel minimum n menurut rumus Slovin?",
             "n = 385 responden (dibulatkan dari 384.6)", "n = 10000 / (1 + 10000 * 0.05²) = 10000 / (1 + 10000 * 0.0025) = 10000 / 26 = 384.62 -> 385 responden."),
            ("Berapakah nilai ambang batas maksimum Cyclomatic Complexity McCabe yang direkomendasikan agar suatu fungsi/metode dianggap mudah diuji dan dirawat?",
             "M <= 10 (Maksimal 10)", "Nilai Cyclomatic Complexity 1-10 dianggap terstruktur baik dan berisiko rendah; nilai > 20 menunjukkan kode kompleks dan berisiko tinggi."),
            ("Metrik DORA manakah yang mengukur persentase rilis deployment ke produksi yang menyebabkan insiden kegagalan layanan?",
             "Change Failure Rate (CFR)", "Change Failure Rate mengukur rasio deployment gagal terhadap total deployment yang dilakukan.")
        ],
        [
            ("Jelaskan perbedaan metodologis antara Simple Random Sampling, Stratified Random Sampling, dan Systematic Sampling dalam survei evaluasi kepuasan sistem informasi kampus (pengguna: Dosen, Mahasiswa, Tenaga Kependidikan)!",
             "1. Simple Random Sampling: Setiap anggota populasi memiliki probabilitas terpilih yang sama secara acak murni tanpa pengelompokan. Kelemahan: Kelompok minoritas (misal Dosen dan Tendik) dapat tidak terwakili secara memadai karena populasi Mahasiswa mendominasi (90%).\n2. Stratified Random Sampling (Paling Tepat): Populasi dibagi ke dalam strata homogen (Strata 1: Dosen, Strata 2: Mahasiswa, Strata 3: Tendik). Sampel acak kemudian ditarik secara proporsional dari masing-masing strata. Menjamin representasi yang adil dan presisi untuk setiap kelompok pemangku kepentingan.\n3. Systematic Sampling: Sampel dipilih berdasarkan interval periodik k (misal setiap kelipatan ke-k dari daftar NIM mahasiswa terurut). Mudah dieksekusi, namun rentan bias jika terdapat pola periodisitas tersembunyi pada urutan data.",
             "Bobot 100: Penjelasan 3 teknik sampling lengkap (45%), analisis kelebihan-kekurangan (30%), justifikasi skenario SIM kampus (25%)."),
            ("Jelaskan konsep Cyclomatic Complexity menurut Thomas McCabe (1976), tuliskan formulanya berdasarkan Control Flow Graph (CFG), dan jelaskan implikasinya terhadap perancangan jumlah skenario pengujian unit (Unit Test Suite)!",
             "Konsep: Mengukur kompleksitas logika kontrol program dan jumlah jalur independen minimum yang melintasi kode program.\nFormula CFG: M = E - N + 2P\ndi mana E = jumlah edge/garis alir, N = jumlah node/titik instruksi, P = jumlah komponen terhubung (P = 1 untuk fungsi tunggal). Alternatif praktis: M = Jumlah Titik Predikat Keputusan (if, while, for, case, &&, ||) + 1.\nImplikasi Unit Testing: Nilai M secara eksak menentukan jumlah kasus uji unit (Unit Test Cases) minimum yang WAJIB dirancang untuk mencapai 100% Branch Coverage (Basis Path Testing). Jika M = 8, tim pengembang wajib menulis setidaknya 8 pengujian unit independen untuk menjamin setiap cabang logika telah teruji.",
             "Bobot 100: Definisi konsep McCabe (30%), formulasi formula CFG lengkap (35%), implikasi terhadap perancangan unit test & branch coverage (35%)."),
            ("Diberikan data metrik 4 tim pengembang software: \n- Tim Alpha: 120 KLOC, 60 Defect, Code Coverage 85%, DORA CFR 5%.\n- Tim Beta: 80 KLOC, 160 Defect, Code Coverage 45%, DORA CFR 25%.\n- Tim Gamma: 150 KLOC, 75 Defect, Code Coverage 90%, DORA CFR 3%.\n- Tim Delta: 50 KLOC, 100 Defect, Code Coverage 50%, DORA CFR 18%.\n(a) Hitung Defect Density (Defect/KLOC) masing-masing tim, (b) Evaluasi korelasi antara Code Coverage dengan Defect Density dan CFR, (c) Berikan rekomendasi teknis untuk tim dengan performa kualitas terendah!",
             "(a) Perhitungan Defect Density:\n- Tim Alpha: 60 / 120 = 0.50 Defect/KLOC\n- Tim Beta: 160 / 80 = 2.00 Defect/KLOC\n- Tim Gamma: 75 / 150 = 0.50 Defect/KLOC\n- Tim Delta: 100 / 50 = 2.00 Defect/KLOC.\n(b) Evaluasi Kualitas: Terdapat korelasi negatif yang sangat kuat antara Code Coverage dengan Defect Density dan Change Failure Rate. Tim dengan coverage pengujian tinggi (Alpha 85%, Gamma 90%) memiliki kepadatan cacat sangat rendah (0.50) dan stabilitas rilis tinggi (CFR <= 5%). Sebaliknya tim dengan coverage rendah (Beta 45%, Delta 50%) memiliki cacat 4x lipat lebih padat (2.00) dan risiko rilis gagal tinggi (CFR 18-25%).\n(c) Rekomendasi untuk Tim Beta: 1) Terapkan Quality Gates di CI/CD pipeline yang mewajibkan minimum Code Coverage 80% sebelum PR dapat di-merge. 2) Lakukan refactoring modul kompleks dengan Cyclomatic Complexity tinggi. 3) Terapkan Automated Regression Testing dan Peer Code Review yang lebih ketat.",
             "Bobot 100: Perhitungan Defect Density 4 tim tepat (35%), analisis evaluasi korelasi metrik mendalam (35%), rekomendasi teknis actionable (30%)."),
            ("Rancang skrip Python untuk mengotomatisasi penarikan sampel acak terstratifikasi (Stratified Random Sampling) dari basis data pengguna log aktivitas sistem menggunakan fungsi train_test_split atau groupby sampling dari Pandas!",
             "Skrip Python:\nimport pandas as pd\n# 1. Stratified Sampling via Pandas\ndef stratified_sample(df, strat_col, sample_size=385, random_state=42):\n    # Hitung proporsi tiap strata\n    strata_counts = df[strat_col].value_counts(normalize=True)\n    sample_list = []\n    for strata, prop in strata_counts.items():\n        n_strata = int(round(prop * sample_size))\n        df_strata = df[df[strat_col] == strata]\n        sample_list.append(df_strata.sample(n=min(len(df_strata), n_strata), random_state=random_state))\n    sampled_df = pd.concat(sample_list).sample(frac=1, random_state=random_state).reset_index(drop=True)\n    print('=== Distribusi Strata Sampel Terpilih ===')\n    print(sampled_df[strat_col].value_counts())\n    return sampled_df",
             "Bobot 100: Logika perhitungan proporsi strata tepat (40%), penarikan sampel acak modular (30%), sintaks kode Python yang rapi dan fungsional (30%).")
        ]
    )

    # Modul 16: Pengukuran Usabilitas: SUS & TAM
    add_module(
        16, "Pengukuran Usabilitas: SUS & TAM", "Buku 2",
        [
            ("Kuesioner System Usability Scale (SUS) standar terdiri dari 10 butir pernyataan dengan skala Likert 1–5. Nilai rata-rata skor SUS standar industri yang dianggap sebagai batas kelayakan usabilitas rata-rata (Grade C / 'OK') adalah:",
             {"A": "50.0", "B": "68.0", "C": "85.0", "D": "100.0", "E": "35.0"}, "B",
             "Berdasarkan riset benchmark usabilitas empiris oleh John Brooke dan Jeff Sauro, skor SUS rata-rata global standar industri adalah 68.0."),
            ("Dalam skema konversi perhitungan skor System Usability Scale (SUS), aturan penskoran untuk butir bernomor ganjil (1, 3, 5, 7, 9) dan butir genap (2, 4, 6, 8, 10) berturut-turut adalah:",
             {"A": "Ganjil: Skor - 1; Genap: 5 - Skor", "B": "Ganjil: 5 - Skor; Genap: Skor - 1", "C": "Ganjil: Skor; Genap: Skor * 2", "D": "Ganjil: Skor + 1; Genap: Skor - 1", "E": "Ganjil dan Genap: Skor * 2.5"}, "A",
             "Formula SUS: Butir bernomor ganjil (pernyataan positif) bernilai (Skor - 1); butir bernomor genap (pernyataan negatif) bernilai (5 - Skor). Total skor kemudian dikalikan 2.5."),
            ("Dua konstruk fundamental dalam model penerimaan teknologi Technology Acceptance Model (TAM) yang dikembangkan oleh Fred Davis (1989) adalah:",
             {"A": "System Efficiency dan Error Rate", "B": "Perceived Usefulness (PU) dan Perceived Ease of Use (PEOU)", "C": "Time to Market dan Cost of Quality", "D": "Usability dan Reliability", "E": "Security dan Scalability"}, "B",
             "TAM mengidentifikasi bahwa penerimaan pengguna terhadap sistem informasi ditentukan oleh dua faktor utama: Perceived Usefulness (Kemanfaatan yang Dirasakan) dan Perceived Ease of Use (Kemudahan Penggunaan yang Dirasakan)."),
            ("Jika sebuah aplikasi mobile banking memperoleh skor rata-rata SUS sebesar 82.5, maka interpretasi Adjective Rating menurut Sauro & Lewis (2011) berada pada kategori:",
             {"A": "Poor (Buruk)", "B": "OK / Marginal", "C": "Good / Excellent (Sangat Baik / Luar Biasa)", "D": "Unacceptable (Tidak Layak)", "E": "Terburuk yang Pernah Ada"}, "C",
             "Skor SUS > 80.3 diklasifikasikan ke dalam Grade A / 'Excellent' (Luar Biasa / Sangat Baik) dan berada di atas persentil ke-90."),
        ],
        [
            ("Berapakah faktor pengali konversi akhir yang digunakan untuk mengubah jumlah skor mentah 10 butir SUS (rentang 0–40) menjadi skala persentil 0–100?",
             "Dikalikan 2.5 (Faktor 2.5)", "Formula SUS: Total Skor Akhir = (Jumlah Skor Termodifikasi Butir 1-10) * 2.5."),
            ("Seorang responden memberikan skor 5 pada butir ke-1 (ganjil) dan skor 1 pada butir ke-2 (genap) kuesioner SUS. Berapakah nilai kontribusi termodifikasi dari kedua butir tersebut?",
             "Total kontribusi = 8 (Butir 1 = 4, Butir 2 = 4)", "Butir 1 (ganjil) = 5 - 1 = 4. Butir 2 (genap) = 5 - 1 = 4. Total = 4 + 4 = 8."),
            ("Tuliskan kepanjangan dari singkatan kuesioner usabilitas standar SUS!",
             "System Usability Scale", "SUS adalah singkatan dari System Usability Scale yang diciptakan oleh John Brooke pada tahun 1986."),
            ("Konstruk TAM manakah yang didefinisikan sebagai 'sejauh mana seseorang percaya bahwa menggunakan sistem akan meningkatkan kinerja pekerjaannya'?",
             "Perceived Usefulness (PU / Persepsi Kemanfaatan)", "Perceived Usefulness mengukur persepsi peningkatan performa dan efektivitas kerja pengguna saat memakai sistem.")
        ],
        [
            ("Jelaskan metodologi dan algoritma perhitungan skor System Usability Scale (SUS) 10 butir secara sistematis, sertakan alasan mengapa format pertanyaan dibuat berselingan antara positif (ganjil) dan negatif (genap)!",
             "Algoritma Perhitungan SUS:\n1. Setiap responden mengisi 10 butir pertanyaan dengan skala Likert 1 (Sangat Tidak Setuju) hingga 5 (Sangat Setuju).\n2. Transformasi Butir Ganjil (Positif: Q1, Q3, Q5, Q7, Q9): Nilai Butir = Skor Jawaban - 1 (rentang 0 s.d. 4).\n3. Transformasi Butir Genap (Negatif: Q2, Q4, Q6, Q8, Q10): Nilai Butir = 5 - Skor Jawaban (rentang 0 s.d. 4).\n4. Penjumlahan Skor: Jumlahkan nilai ke-10 butir yang telah ditransformasi (rentang total 0 s.d. 40).\n5. Penskalaan Akhir: Kalikan total jumlah dengan 2.5 sehingga diperoleh skor akhir SUS berskala 0 s.d. 100.\nAlasan Pergantian Positif-Negatif: Format selang-seling dirancang secara psikometrik untuk mencegah 'Acquiescence Bias' (kecenderungan responden menyetujui semua pernyataan secara malas/autopilot) dan mendeteksi responden yang tidak membaca pertanyaan secara saksama.",
             "Bobot 100: Langkah matematis perhitungan ganjil-genap tepat (40%), faktor pengali 2.5 tepat (20%), justifikasi pencegahan acquiescence bias (40%)."),
            ("Diberikan respon kuesioner SUS 10 butir dari seorang pengguna terhadap prototipe aplikasi: \nQ1 (ganjil) = 4, Q2 (genap) = 2, Q3 (ganjil) = 5, Q4 (genap) = 1, Q5 (ganjil) = 4, \nQ6 (genap) = 2, Q7 (ganjil) = 5, Q8 (genap) = 2, Q9 (ganjil) = 4, Q10 (genap) = 1.\n(a) Hitung skor kontribusi tiap butir dan skor total akhir SUS pengguna tersebut! \n(b) Evaluasi posisi skor tersebut terhadap standar industri 68.0 dan tentukan Grade serta Adjective Rating-nya menurut Sauro & Lewis!",
             "(a) Perhitungan Kontribusi Butir:\n- Butir Ganjil (Skor - 1): Q1 = 4-1=3; Q3 = 5-1=4; Q5 = 4-1=3; Q7 = 5-1=4; Q9 = 4-1=3. (Total Ganjil = 3+4+3+4+3 = 17)\n- Butir Genap (5 - Skor): Q2 = 5-2=3; Q4 = 5-1=4; Q6 = 5-2=3; Q8 = 5-2=3; Q10 = 5-1=4. (Total Genap = 3+4+3+3+4 = 17)\n- Total Skor Mentah = 17 + 17 = 34.\n- Skor Akhir SUS = 34 * 2.5 = 85.0.\n(b) Evaluasi Usabilitas: Skor 85.0 berada jauh di atas rata-rata benchmark industri (68.0). Menurut Sauro & Lewis (2011), skor 85.0 masuk ke dalam Grade A / Adjective Rating 'Excellent' (Luar Biasa), menunjukkan tingkat penerimaan usabilitas yang sangat tinggi (Acceptable) dan berada di atas persentil ke-95.",
             "Bobot 100: Perhitungan kontribusi butir ganjil-genap tepat (40%), perhitungan skor akhir SUS tepat (30%), evaluasi benchmark industri & Adjective Rating tepat (30%)."),
            ("Jelaskan kerangka teoritis Technology Acceptance Model (TAM) menurut Fred Davis (1989): Bagaimana hubungan kausalitas antara External Variables, Perceived Ease of Use (PEOU), Perceived Usefulness (PU), Attitude Toward Using (ATU), Behavioral Intention (BI), dan Actual System Usage (ASU)?",
             "Struktur Kausalitas TAM:\n1. External Variables (Kualitas UI/UX, Pelatihan, Fitur Sistem) mempengaruhi secara langsung persepsi pengguna: PEOU dan PU.\n2. Perceived Ease of Use (PEOU) mempengaruhi Perceived Usefulness (PU): Sistem yang semakin mudah digunakan akan dirasakan semakin bermanfaat.\n3. PEOU dan PU bersama-sama membentuk Attitude Toward Using (ATU / Sikap Positif terhadap Sistem).\n4. PU dan ATU menentukan Behavioral Intention (BI / Niat Perilaku Penggunaan).\n5. Behavioral Intention (BI) secara langsung mendorong Actual System Usage (ASU / Penggunaan Sistem Nyata di Kehidupan Sehari-hari).\nImplikasi Desain: Desainer UI/UX harus memprioritaskan kemudahan navigasi (PEOU) karena kemudahan adalah pintu gerbang utama yang mendorong persepsi manfaat (PU) dan adopsi aktual sistem.",
             "Bobot 100: Penjelasan alur kausalitas 6 konstruk TAM lengkap (60%), hubungan PEOU thd PU (20%), implikasi desain rekayasa perangkat lunak (20%)."),
            ("Rancang fungsi Python untuk menghitung skor SUS otomatis dari DataFrame pandas yang memuat 10 kolom pertanyaan kuesioner ('sus_q1' s.d. 'sus_q10') dan menambahkan kolom klasifikasi predikat kelayakan usabilitas!",
             "Skrip Python:\nimport pandas as pd, numpy as np\ndef calculate_sus_score(df):\n    # 1. Butir Ganjil (Q1, Q3, Q5, Q7, Q9)\n    odd_cols = ['sus_q1', 'sus_q3', 'sus_q5', 'sus_q7', 'sus_q9']\n    odd_sum = df[odd_cols].apply(lambda x: x - 1).sum(axis=1)\n    # 2. Butir Genap (Q2, Q4, Q6, Q8, Q10)\n    even_cols = ['sus_q2', 'sus_q4', 'sus_q6', 'sus_q8', 'sus_q10']\n    even_sum = df[even_cols].apply(lambda x: 5 - x).sum(axis=1)\n    # 3. Skor Total SUS\n    df['sus_score'] = (odd_sum + even_sum) * 2.5\n    # 4. Predikat Usabilitas Sauro-Lewis\n    conditions = [\n        (df['sus_score'] >= 80.3),\n        (df['sus_score'] >= 68.0) & (df['sus_score'] < 80.3),\n        (df['sus_score'] >= 51.0) & (df['sus_score'] < 68.0),\n        (df['sus_score'] < 51.0)\n    ]\n    grades = ['Grade A (Excellent)', 'Grade B/C (Good/OK)', 'Grade D (Poor)', 'Grade F (Unacceptable)']\n    df['sus_grade'] = np.select(conditions, grades)\n    return df",
             "Bobot 100: Transformasi vektor kolom ganjil & genap efisien (40%), formula pengali 2.5 tepat (20%), penambahan kategori predikat tepat (40%).")
        ]
    )

    # Modul 17: Uji Validitas Butir & Reliabilitas Cronbach's Alpha
    add_module(
        17, "Uji Validitas Butir & Reliabilitas Cronbach's Alpha", "Buku 2",
        [
            ("Uji validitas butir instrumen kuesioner menggunakan korelasi Pearson (Item-Total Correlation) menetapkan bahwa suatu butir pertanyaan dinyatakan VALID jika nilai r-hitung memenuhi kriteria:",
             {"A": "r-hitung > r-tabel (atau r-hitung >= 0.30)", "B": "r-hitung < 0", "C": "r-hitung = 0", "D": "p-value > 0.05", "E": "Nilai r-hitung negatif konstan"}, "A",
             "Kriteria standar psikometrik empiris (Azwar, 2012) menetapkan bahwa butir kuesioner valid jika nilai corrected item-total correlation r >= 0.30 atau r-hitung > r-tabel pada taraf signifikansi 5%."),
            ("Koefisien reliabilitas konsistensi internal Cronbach's Alpha (alpha) dianggap memenuhi standar kelayakan reliabilitas instrumen yang baik jika bernilai:",
             {"A": "alpha >= 0.70", "B": "0.10 <= alpha <= 0.30", "C": "alpha < 0", "D": "alpha = 0.50", "E": "alpha >= 0.99 murni"}, "A",
             "Standar konvensi ilmiah (Nunnally, 1978) menetapkan bahwa batas ambang minimum instrumen penelitian yang reliabel/konsisten adalah Cronbach's Alpha alpha >= 0.70."),
            ("Formula Cronbach's Alpha alpha = [k / (k - 1)] * [1 - (sum(sigma_i²) / sigma_total²)] memperhitungkan rasio antara:",
             {"A": "Jumlah varians masing-masing butir terhadap varians skor total kuesioner", "B": "Rata-rata butir terhadap ukuran sampel", "C": "Jumlah responden terhadap jumlah butir", "D": "Standar deviasi butir terhadap nilai median", "E": "Nilai maksimum terhadap minimum"}, "A",
             "Formula Cronbach's Alpha mengukur sejauh mana varians total dijelaskan oleh kovarians bersama antar butir dibandingkan dengan jumlah varians individual butir sum(sigma_i²)."),
            ("Analisis 'Alpha if Item Deleted' (Reliabilitas jika Butir Dihapus) digunakan untuk:",
             {"A": "Menghitung rata-rata skor kuesioner", "B": "Mengidentifikasi butir pertanyaan yang cacat/inkonsisten yang jika dieliminasi akan menaikkan nilai reliabilitas instrumen secara signifikan", "C": "Menghapus data responden secara otomatis", "D": "Menguji normalitas data", "E": "Mengurangi jumlah sampel responden"}, "B",
             "Jika nilai 'Alpha if Item Deleted' dari suatu butir lebih tinggi daripada nilai Cronbach's Alpha keseluruhan saat ini, maka butir tersebut merusak konsistensi internal kuesioner dan disarankan untuk dihapus/direvisi.")
        ],
        [
            ("Jika sebuah kuesioner survei terdiri dari k = 10 butir pertanyaan dengan jumlah varians butir sum(sigma_i²) = 4.5 dan varians skor total sigma_total² = 25.0, berapakah nilai Cronbach's Alpha-nya?",
             "Cronbach's Alpha = 0.911", "alpha = (10 / 9) * [1 - (4.5 / 25.0)] = 1.111 * [1 - 0.18] = 1.111 * 0.82 = 0.911."),
            ("Berapakah batas nilai korelasi Item-Total Correlation (r) minimum yang umum digunakan untuk menyatakan butir kuesioner valid secara empiris?",
             "r >= 0.30 (atau r-hitung > r-tabel)", "Batas konvensi empiris r >= 0.30 menunjukkan bahwa butir berkontribusi positif terhadap konstruk variabel yang diukur."),
            ("Apakah arti istilah 'Konsistensi Internal' (Internal Consistency) dalam pengujian reliabilitas instrumen kuesioner?",
             "Sejauh mana butir-butir pertanyaan dalam satu instrumen saling berkorelasi dan konsisten dalam mengukur konstruk laten yang sama", "Konsistensi internal memastikan semua butir pertanyaan mengukur dimensi variabel yang sama tanpa kontradiksi."),
            ("Sebutkan fungsi pustaka Pingouin Python yang digunakan untuk menghitung koefisien Cronbach's Alpha secara langsung!",
             "pingouin.cronbach_alpha()", "Fungsi pingouin.cronbach_alpha(data=df) menghitung nilai alpha dan confidence interval 95% secara otomatis.")
        ],
        [
            ("Jelaskan perbedaan mendasar antara konsep 'Validitas' dan 'Reliabilitas' dalam perancangan instrumen pengukuran rekayasa perangkat lunak dan evaluasi UI/UX, serta berikan analogi target tembak (bullseye)!",
             "1. Validitas (Akurasi / Ketepatan Ukur): Mengukur sejauh mana instrumen benar-benar mengukur apa yang seharusnya diukur. Contoh: Kuesioner dirancang untuk mengukur 'Beban Kerja Kognitif Pengguna', bukan sekadar 'Estetika Visual'.\n2. Reliabilitas (Presisi / Konsistensi): Mengukur sejauh mana instrumen menghasilkan hasil pengukuran yang stabil dan konsisten jika diulang pada kondisi yang sama.\nAnalogi Target Tembak (Bullseye):\n- Reliabel tapi Tidak Valid: Tembakan mengelompok rapat dan konsisten di satu titik, tetapi jauh meleset di pojok target (bukan di titik tengah bullseye).\n- Valid tapi Tidak Reliabel: Tembakan tersebar acak di sekitar titik tengah bullseye tanpa pola yang rapat dan konsisten.\n- Tidak Valid & Tidak Reliabel: Tembakan tersebar acak di luar target.\n- Valid dan Reliabel (Ideal): Tembakan mengelompok sangat rapat tepat di titik tengah bullseye target.",
             "Bobot 100: Definisi Validitas & Reliabilitas tepat (40%), analogi target tembak lengkap dan jelas (40%), relevansi instrumen software UI/UX (20%)."),
            ("Diberikan data hasil uji coba instrumen 5 butir pertanyaan TAM (k = 5) pada 30 responden. Varians masing-masing butir adalah: sigma_1² = 0.60, sigma_2² = 0.70, sigma_3² = 0.50, sigma_4² = 0.80, sigma_5² = 0.60. Varians skor total kuesioner adalah sigma_total² = 8.00. (a) Hitunglah nilai koefisien Cronbach's Alpha instrumen tersebut! (b) Evaluasi status reliabilitas instrumen berdasarkan standar Nunnally (alpha >= 0.70)!",
             "(a) Perhitungan Cronbach's Alpha:\n- Jumlah Butir k = 5, sehingga k / (k - 1) = 5 / 4 = 1.25.\n- Jumlah Varians Butir sum(sigma_i²) = 0.60 + 0.70 + 0.50 + 0.80 + 0.60 = 3.20.\n- Rasio Varians = sum(sigma_i²) / sigma_total² = 3.20 / 8.00 = 0.40.\n- Nilai Alpha = [k / (k - 1)] * [1 - (sum(sigma_i²) / sigma_total²)]\n  alpha = 1.25 * (1 - 0.40) = 1.25 * 0.60 = 0.750.\n(b) Evaluasi Reliabilitas: Nilai Cronbach's Alpha yang diperoleh adalah 0.750. Karena 0.750 >= 0.70, instrumen kuesioner dinyatakan RELIABEL / MEMENUHI KONSISTENSI INTERNAL yang baik menurut standar Nunnally (1978) dan layak digunakan untuk pengumpulan data penelitian.",
             "Bobot 100: Langkah perhitungan varians dan substitusi rumus tepat (50%), nilai akhir alpha tepat (20%), evaluasi standar Nunnally tepat (30%)."),
            ("Jelaskan prosedur diagnostik 'Alpha if Item Deleted' dalam pengujian kuesioner: Apa indikator matematis bahwa suatu butir pertanyaan harus dieliminasi, dan mengapa butir yang buruk dapat menurunkan reliabilitas keseluruhan instrumen?",
             "Prosedur Alpha if Item Deleted:\n1. Algoritma menghitung nilai Cronbach's Alpha awal untuk seluruh k butir (misal alpha_awal = 0.65).\n2. Secara bergantian, algoritma mengeluarkan butir ke-j dan menghitung ulang Cronbach's Alpha untuk sisa (k - 1) butir.\n3. Kriteria Eliminasi: Jika terdapat butir j yang nilai 'Alpha if Item Deleted'-nya meningkat secara signifikan (misal melonjak menjadi 0.82 jika butir j dibuang), maka butir j diidentifikasi sebagai BUTIR RUSAK / TIDAK KONSISTEN.\nAlasan Penurunan Reliabilitas: Butir yang buruk biasanya memiliki korelasi negatif atau mendekati nol dengan butir-butir lainnya (misal: kalimat pertanyaan ambigu, membingungkan, atau mengukur konsep yang berbeda). Butir ini menambah varians galat individual sum(sigma_i²) tanpa menambah kovarians bersama pada varians total sigma_total², sehingga menekan nilai Alpha ke bawah.",
             "Bobot 100: Penjelasan mekanisme iterasi komputasi (40%), kriteria eliminasi matematis (30%), analisis teoritis mengapa butir buruk merusak alpha (30%)."),
            ("Tuliskan skrip Python lengkap untuk: (1) Menguji validitas butir menggunakan korelasi Corrected Item-Total Pearson, (2) Menghitung Cronbach's Alpha keseluruhan, dan (3) Menghitung tabel diagnostik 'Alpha if Item Deleted' untuk setiap kolom pertanyaan!",
             "Skrip Python:\nimport pandas as pd, numpy as np\n# df_items berisi kolom item_1 s.d. item_k\ndef item_reliability_analysis(df):\n    k = df.shape[1]\n    total_score = df.sum(axis=1)\n    # 1. Corrected Item-Total Correlation\n    validity = {}\n    for col in df.columns:\n        rest_score = total_score - df[col]\n        validity[col] = df[col].corr(rest_score)\n    # 2. Overall Cronbach Alpha\n    var_items = df.var(ddof=1).sum()\n    var_total = total_score.var(ddof=1)\n    alpha_overall = (k / (k - 1)) * (1 - var_items / var_total)\n    # 3. Alpha if Item Deleted\n    alpha_deleted = {}\n    for col in df.columns:\n        df_sub = df.drop(columns=[col])\n        k_sub = k - 1\n        tot_sub = df_sub.sum(axis=1)\n        alpha_deleted[col] = (k_sub / (k_sub - 1)) * (1 - df_sub.var(ddof=1).sum() / tot_sub.var(ddof=1))\n    # Hasil DataFrame\n    report = pd.DataFrame({\n        'Item-Total Correlation': validity,\n        'Status Validitas (r >= 0.30)': ['VALID' if r >= 0.30 else 'INVALID' for r in validity.values()],\n        'Alpha if Item Deleted': alpha_deleted\n    })\n    print(f'Cronbach Alpha Keseluruhan: {alpha_overall:.4f}')\n    return report",
             "Bobot 100: Perhitungan Corrected Item-Total Correlation tepat (35%), formula Cronbach Alpha tepat (30%), pembuatan tabel Alpha if Item Deleted modular (35%).")
        ]
    )

    # Modul 18: Uji Kesepakatan Evaluator QA (Cohen's Kappa)
    add_module(
        18, "Uji Kesepakatan Evaluator QA (Cohen's Kappa)", "Buku 2",
        [
            ("Uji Cohen's Kappa (kappa) digunakan dalam Software Quality Assurance (QA) untuk mengukur tingkat kesepakatan klasifikasi bug antar:",
             {"A": "Dua evaluator / penilai independen dengan mengoreksi faktor kesepakatan kebetulan acak (chance agreement)", "B": "Seratus pengguna aplikasi", "C": "Dua server database", "D": "Versi arsitektur microservices", "E": "Rasio kompresi file"}, "A",
             "Cohen's Kappa mengukur reliabilitas inter-rater antara 2 penilai kategorikal dengan rumus kappa = (P_o - P_e) / (1 - P_e), di mana P_e adalah peluang kesepakatan kebetulan acak."),
            ("Jika dua rater QA memiliki observed agreement P_o = 0.85 dan expected chance agreement P_e = 0.50, maka nilai Cohen's Kappa adalah:",
             {"A": "0.35", "B": "0.70", "C": "0.85", "D": "1.00", "E": "0.50"}, "B",
             "kappa = (P_o - P_e) / (1 - P_e) = (0.85 - 0.50) / (1 - 0.50) = 0.35 / 0.50 = 0.70."),
            ("Berdasarkan skala Landis & Koch (1977), nilai Cohen's Kappa pada rentang 0.61 – 0.80 dikategorikan ke dalam tingkat kesepakatan:",
             {"A": "Slight (Sangat Rendah)", "B": "Fair (Cukup)", "C": "Moderate (Sedang)", "D": "Substantial (Tinggi / Kuat)", "E": "Almost Perfect (Hampir Sempurna)"}, "D",
             "Skala Landis & Koch: 0.00-0.20 (Slight), 0.21-0.40 (Fair), 0.41-0.60 (Moderate), 0.61-0.80 (Substantial), 0.81-1.00 (Almost Perfect)."),
            ("Mengapa metrik persentase kesepakatan sederhana (Percentage Agreement / P_o) dianggap cacat dalam mengevaluasi kesepakatan rater QA?",
             {"A": "Karena nilainya selalu bernilai negatif", "B": "Karena gagal mengoreksi peluang kesepakatan semu yang terjadi murni karena faktor kebetulan acak", "C": "Karena hanya dapat dihitung pada sampel n < 10", "D": "Karena memerlukan uji normalitas data", "E": "Karena tidak dapat diprogram di Python"}, "B",
             "Persentase kesepakatan murni P_o rentan bias tinggi, terutama jika ada satu kategori kelas yang sangat mendominasi (misal 90% bug adalah Minor), di mana dua rater yang menebak acak pun akan tampak sepakat tinggi secara semu.")
        ],
        [
            ("Tuliskan formula matematis indeks Cohen's Kappa (kappa)!",
             "kappa = (P_o - P_e) / (1 - P_e)", "P_o adalah proporsi kesepakatan teramati (observed agreement), dan P_e adalah proporsi kesepakatan ekspektasi peluang acak (chance agreement)."),
            ("Berapakah nilai Cohen's Kappa jika tingkat kesepakatan aktual kedua penilai tepat sama persis dengan kesepakatan peluang kebetulan acak (P_o = P_e)?",
             "kappa = 0.0", "Jika P_o = P_e, maka pembilang (P_o - P_e) = 0, sehingga kappa = 0 (tidak ada kesepakatan di atas kebetulan acak)."),
            ("Sebutkan fungsi dalam pustaka Scikit-Learn Python yang digunakan untuk menghitung skor Cohen's Kappa!",
             "sklearn.metrics.cohen_kappa_score(rater1, rater2)", "Fungsi cohen_kappa_score menghitung nilai Cohen's Kappa antara dua array penilaian rater."),
            ("Jika nilai Cohen's Kappa bernilai negatif (kappa < 0), apakah artinya?",
             "Tingkat kesepakatan aktual lebih buruk/lebih rendah daripada kesepakatan tebakan acak murni (ketidaksepakatan sistematis)", "Nilai negatif menandakan adanya bias sistematis di mana kedua rater cenderung saling bertentangan dalam penilaian.")
        ],
        [
            ("Dua insinyur QA (Rater 1 dan Rater 2) mengklasifikasikan 100 bug ke dalam 2 kategori: 'Kritis' dan 'Biasa'. Tabel kontingensi kesepakatan menunjukkan:\n- Rater 1 Kritis & Rater 2 Kritis = 40\n- Rater 1 Kritis & Rater 2 Biasa = 10\n- Rater 1 Biasa & Rater 2 Kritis = 10\n- Rater 1 Biasa & Rater 2 Biasa = 40\n(a) Hitunglah nilai Observed Agreement (P_o), (b) Hitunglah Expected Chance Agreement (P_e), (c) Hitunglah indeks Cohen's Kappa (kappa), dan (d) Berikan interpretasi tingkat kesepakatannya menurut Landis & Koch!",
             "(a) Observed Agreement (P_o):\nJumlah sepakat di diagonal utama = 40 + 40 = 80.\nP_o = 80 / 100 = 0.80 (80.0%).\n(b) Expected Chance Agreement (P_e):\n- Total Rater 1 Kritis = 40 + 10 = 50 (Proporsi p1_K = 0.50); Biasa = 50 (Proporsi p1_B = 0.50).\n- Total Rater 2 Kritis = 40 + 10 = 50 (Proporsi p2_K = 0.50); Biasa = 50 (Proporsi p2_B = 0.50).\n- P_e = (p1_K * p2_K) + (p1_B * p2_B) = (0.50 * 0.50) + (0.50 * 0.50) = 0.25 + 0.25 = 0.50 (50.0%).\n(c) Indeks Cohen's Kappa:\nkappa = (P_o - P_e) / (1 - P_e) = (0.80 - 0.50) / (1 - 0.50) = 0.30 / 0.50 = 0.600.\n(d) Interpretasi Landis & Koch: Nilai kappa = 0.600 berada pada batas atas kategori 'Moderate Agreement' (Kesepakatan Sedang). Menunjukkan kesepakatan klasifikasi bug yang cukup memadai, namun masih membutuhkan standarisasi rubrik QA untuk mencapai kategori Substantial (> 0.60).",
             "Bobot 100: Perhitungan P_o tepat (25%), perhitungan P_e tepat (35%), perhitungan nilai kappa tepat (25%), interpretasi Landis & Koch tepat (15%)."),
            ("Jelaskan fenomena 'The Kappa Paradox' (High Agreement but Low Kappa): Mengapa dua rater yang memiliki persentase kesepakatan teramati sangat tinggi (misal P_o = 92%) dapat menghasilkan nilai Cohen's Kappa yang sangat rendah mendekati nol?",
             "Penyebab Paradox Kappa: Terjadi ketika terdapat ketidakseimbangan prevalensi kelas yang ekstrem (Prevalence Asymmetry). Misalkan dalam 100 bug produksi, 95 bug adalah 'Minor' dan hanya 5 bug 'Critical'.\n- Jika kedua rater sama-sama menilai 'Minor' pada 90 bug, dan saling tidak sepakat pada 10 bug lainnya, maka P_o = 90 / 100 = 0.90 (90%).\n- Namun, karena proporsi kelas Minor sangat dominan pada kedua rater (p1_Minor = 0.95, p2_Minor = 0.95), nilai peluang kebetulan P_e menjadi sangat tinggi: P_e ~ (0.95 * 0.95) = 0.9025.\n- Akibatnya, nilai Kappa: kappa = (0.90 - 0.9025) / (1 - 0.9025) = -0.025 / 0.0975 = -0.256.\nInterpretasi: Meskipun secara visual rater sepakat pada 90% kasus, kesepakatan tersebut murni didorong oleh dominasi kelas mayoritas, bukan karena kemampuan diskriminasi rater pada kelas langka. Solusi: Gunakan Prevalence-Adjusted Bias-Adjusted Kappa (PABAK).",
             "Bobot 100: Analisis penyebab ketidakseimbangan prevalensi (40%), ilustrasi numerik paradoks kappa (40%), solusi PABAK (20%)."),
            ("Mengapa evaluasi Inter-Rater Reliability (Cohen's Kappa) sangat krusial dalam pembangunan dataset Machine Learning Supervised (seperti pelabelan sentimen teks ulasan atau deteksi ujaran kebencian)?",
             "Signifikansi dalam ML Dataset Annotation:\n1. Kualitas Ground Truth: Model machine learning supervised hanya bisa sebaik kualitas label data latihnya (Garbage In, Garbage Out). Jika antar-annotator memiliki kesepakatan rendah (kappa < 0.40), label target menjadi ambigu dan model akan gagal belajar pola pemisah yang valid.\n2. Mengidentifikasi Definisi Label yang Kabur: Kappa rendah mengindikasikan bahwa panduan anotasi (annotation guidelines) memiliki celah ambiguitas yang perlu diperbaiki.\n3. Eliminasi Bias Anotator: Mengetahui apakah seorang annotator tertentu memiliki bias personal sistematis dibanding annotator lain.\n4. Standar Batas Kelayakan Rilis Dataset: Dalam riset NLP/CV internasional, dataset latih baru dianggap layak dirilis jika memiliki nilai Kappa >= 0.70 (Substantial Agreement).",
             "Bobot 100: Analisis dampak kualitas ground truth ML (40%), perbaikan panduan anotasi (30%), standar batas kelayakan rilis dataset (30%)."),
            ("Rancang skrip Python menggunakan Scikit-Learn dan Seaborn untuk: (1) Menghitung matriks kontingensi (confusion_matrix) antara Rater 1 dan Rater 2, (2) Menghitung nilai Cohen's Kappa, dan (3) Memvisualisasikan heatmap matriks kesepakatan dengan annotasi nilai frekuensi!",
             "Skrip Python:\nimport pandas as pd, matplotlib.pyplot as plt, seaborn as sns\nfrom sklearn.metrics import cohen_kappa_score, confusion_matrix\n# 1. Matriks Kesepakatan & Kappa\nlabels = ['Minor', 'Major', 'Critical']\ncm = confusion_matrix(df_qa['rater_1'], df_qa['rater_2'], labels=labels)\nkappa_val = cohen_kappa_score(df_qa['rater_1'], df_qa['rater_2'])\nprint(f'=== Hasil Uji Cohen Kappa QA ===')\nprint(f'Nilai Kappa: {kappa_val:.4f}')\n# 2. Visualisasi Heatmap\nplt.figure(figsize=(7, 5))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)\nplt.title(f'Matriks Kesepakatan QA (Cohen Kappa = {kappa_val:.3f})', fontweight='bold')\nplt.xlabel('Evaluator QA 2'); plt.ylabel('Evaluator QA 1')\nplt.tight_layout(); plt.show()",
             "Bobot 100: Eksekusi cohen_kappa_score tepat (35%), matriks kontingensi tepat (30%), visualisasi sns.heatmap rapi (35%).")
        ]
    )

    # Modul 19: Weighted & Fleiss' Kappa Multi-Pakar
    add_module(
        19, "Weighted & Fleiss' Kappa Multi-Pakar", "Buku 2",
        [
            ("Penggunaan Weighted Kappa (Kappa Berbobot) lebih diutamakan daripada Cohen's Kappa standar jika data klasifikasi berskala:",
             {"A": "Nominal murni", "B": "Ordinal berjenjang (seperti Severity: Minor < Major < Critical)", "C": "Kontinu tanpa batas", "D": "Biner 0 dan 1", "E": "Deret waktu"}, "B",
             "Weighted Kappa memperhitungkan derajat ketidaksepakatan ordinal, di mana ketidaksepakatan antara 'Minor' vs 'Critical' diberi bobot penalti jauh lebih berat daripada 'Minor' vs 'Major'."),
            ("Uji statistik kesepakatan antar-penilai yang digunakan saat jumlah evaluator/pakar berjumlah LEBIH DARI DUA ORANG (Multi-Rater, misal 5 pakar UI/UX) adalah:",
             {"A": "Cohen's Kappa", "B": "Fleiss' Kappa", "C": "Uji-t Berpasangan", "D": "Regresi Linier", "E": "Koefisien Pearson"}, "B",
             "Fleiss' Kappa adalah generalisasi statistik dari Cohen's Kappa yang dirancang khusus untuk mengukur kesepakatan kategorikal antar sejumlah rater tetap (> 2 rater)."),
            ("Dalam skema pembobotan kuadratik (Quadratic Weighted Kappa / QWK) untuk k tingkatan skala ordinal, bobot penalti selisih jarak antara kategori i dan j dihitung dengan rumus:",
             {"A": "w_ij = |i - j|", "B": "w_ij = (i - j)² / (k - 1)²", "C": "w_ij = i * j", "D": "w_ij = 1 - (i / j)", "E": "w_ij = sqrt(i - j)"}, "B",
             "Quadratic Weighted Kappa memberikan penalti kuadratik w_ij = (i - j)² / (k - 1)² yang menghukum ketidaksepakatan ekstrem secara proporsional lebih berat."),
            ("Jika sebuah evaluasi heuristik antarmuka oleh 4 pakar UI/UX menghasilkan Fleiss' Kappa kappa = 0.82, maka kesimpulannya adalah:",
             {"A": "Terdapat ketidaksepakatan total antar pakar", "B": "Tingkat kesepakatan antar pakar sangat tinggi (Almost Perfect Agreement)", "C": "Uji heuristik harus diulang", "D": "Data tidak valid", "E": "Desain UI harus ditolak"}, "B",
             "Nilai Fleiss' Kappa > 0.80 menunjukkan tingkat konsistensi dan kesepakatan yang hampir sempurna (Almost Perfect Agreement) di antara seluruh pakar evaluasi.")
        ],
        [
            ("Apakah perbedaan utama antara Cohen's Kappa dan Fleiss' Kappa dalam hal jumlah penilai (rater)?",
             "Cohen's Kappa untuk tepat 2 penilai; Fleiss' Kappa untuk lebih dari 2 penilai (> 2 rater)", "Cohen's Kappa dibatasi untuk 2 rater, sedangkan Fleiss' Kappa mengakomodasi banyak rater (multi-rater)."),
            ("Sebutkan dua jenis skema pembobotan yang umum digunakan pada Weighted Kappa!",
             "Linear Weights dan Quadratic Weights", "Linear Weights memberikan penalti linier proporsional selisih tingkat, sedangkan Quadratic Weights memberikan penalti kuadratik."),
            ("Pustaka Python manakah (dalam modul statsmodels) yang menyediakan fungsi fleiss_kappa untuk menghitung kesepakatan multi-rater?",
             "statsmodels.stats.inter_rater.fleiss_kappa", "Modul statsmodels.stats.inter_rater menyediakan fungsi agregasi fleiss_kappa."),
            ("Format tabel matriks input apakah yang dibutuhkan oleh fungsi fleiss_kappa dalam Python?",
             "Matriks berukuran N objek x k kategori (di mana nilai sel adalah jumlah rater yang memilih kategori k pada objek N)", "Fleiss Kappa membutuhkan matriks frekuensi pemilihan kategori per subjek yang dievaluasi.")
        ],
        [
            ("Jelaskan perbedaan fundamental antara Unweighted Cohen's Kappa, Linear Weighted Kappa, dan Quadratic Weighted Kappa dalam evaluasi tingkat keparahan bug perangkat lunak (Minor = 1, Major = 2, Critical = 3)!",
             "1. Unweighted Cohen's Kappa: Memperlakukan semua ketidaksepakatan secara setara tanpa memandang jarak ordinal. Perbedaan pendapat antara (Minor vs Major) dianggap sama bobot kesalahannya dengan (Minor vs Critical).\n2. Linear Weighted Kappa: Memberikan penalti linier berdasarkan selisih jarak ordinal: w_ij = 1 - (|i - j| / (k - 1)). Ketidaksepakatan selisih 1 tingkat (Minor vs Major) dihukum penalti 0.50, sedangkan selisih 2 tingkat (Minor vs Critical) dihukum penalti 1.00.\n3. Quadratic Weighted Kappa (QWK): Memberikan penalti kuadratik: w_ij = 1 - ((i - j)² / (k - 1)²). Selisih 1 tingkat hanya dihukum penalti (1/2)² = 0.25 (toleransi lebih tinggi), namun selisih 2 tingkat ekstrem dihukum penalti penuh (2/2)² = 1.00.\nDalam QA Software: QWK adalah standar emas karena perbedaan minor vs critical adalah kesalahan fatal yang harus dihukum sangat berat.",
             "Bobot 100: Penjelasan Unweighted Kappa (30%), Linear Weighted Kappa (35%), Quadratic Weighted Kappa & aplikasinya di QA (35%)."),
            ("Jelaskan secara sistematis algoritma perhitungan Fleiss' Kappa untuk N subjek yang dinilai oleh n rater ke dalam k kategori, termasuk cara menghitung P_i (proporsi kesepakatan subjek ke-i), P_bar (rata-rata kesepakatan observasi), dan P_e_bar (rata-rata kesepakatan peluang acak)!",
             "Algoritma Fleiss' Kappa:\n1. Struktur Data: Diberikan matriks r x k di mana n_ij adalah jumlah rater yang memasukkan subjek i ke kategori j. Total rater per subjek adalah n = sum_j n_ij.\n2. Kesepakatan Subjek ke-i (P_i):\nP_i = [1 / (n * (n - 1))] * [ (sum_{j=1}^k n_ij²) - n ]\n3. Rata-rata Kesepakatan Teramati (P_bar):\nP_bar = (1 / N) * sum_{i=1}^N P_i\n4. Proporsi Keseluruhan Kategori ke-j (p_j):\np_j = (1 / (N * n)) * sum_{i=1}^N n_ij\n5. Rata-rata Kesepakatan Peluang Acak (P_e_bar):\nP_e_bar = sum_{j=1}^k p_j²\n6. Indeks Fleiss' Kappa Akhir:\nkappa = (P_bar - P_e_bar) / (1 - P_e_bar).",
             "Bobot 100: Formulasi P_i dan P_bar tepat (40%), formulasi p_j dan P_e_bar tepat (40%), rumus akhir Fleiss Kappa tepat (20%)."),
            ("Sebuah tim UX Designer meminta 4 pakar independen (n = 4) untuk mengevaluasi 10 komponen antarmuka sistem (N = 10) ke dalam 3 status: 'Lolos', 'Revisi', 'Tolak'. Jelaskan bagaimana metodologi Fleiss' Kappa membantu tim memutuskan apakah hasil evaluasi pakar konsisten atau terdapat friksi standar pengujian antar pakar!",
             "Analisis Metodologi:\n1. Menguji Konsistensi Objektif: Jika Fleiss' Kappa kappa >= 0.75, tim UX memiliki bukti empiris bahwa ke-4 pakar memiliki persepsi dan standar evaluasi yang seragam. Komponen yang berstatus 'Tolak' dapat langsung dirombak tanpa ragu.\n2. Mendeteksi Friksi & Ambiguitas Rubrik: Jika kappa < 0.40 (Poor/Fair Agreement), ini membuktikan adanya friksi standar atau pedoman evaluasi heuristik (Nielsen's Heuristics) yang multitafsir di antara para pakar. Tim tidak boleh langsung mengubah desain, melainkan harus mengadakan Focus Group Discussion (FGD) untuk menyelaraskan rubrik penilaian terlebih dahulu.\n3. Nilai Tambah vs Rata-rata: Fleiss' Kappa jauh lebih akurat dibanding voting mayoritas sederhana karena mengeliminasi faktor kebetulan acak voting.",
             "Bobot 100: Analisis interpretasi konsistensi pakar (40%), deteksi friksi rubrik evaluasi (35%), justifikasi metodologis vs voting biasa (25%)."),
            ("Tuliskan skrip Python untuk: (1) Menghitung Quadratic Weighted Kappa antara 2 rater menggunakan Scikit-Learn, dan (2) Menghitung Fleiss' Kappa untuk multi-rater menggunakan fungsi statsmodels!",
             "Skrip Python:\nimport numpy as np, pandas as pd\nfrom sklearn.metrics import cohen_kappa_score\nfrom statsmodels.stats.inter_rater import fleiss_kappa, aggregate_raters\n# 1. Quadratic Weighted Kappa (2 Raters)\nrater1 = [1, 2, 3, 2, 1, 3, 2, 3]\nrater2 = [1, 2, 2, 2, 1, 3, 1, 3]\nqwk = cohen_kappa_score(rater1, rater2, weights='quadratic')\nprint(f'Quadratic Weighted Kappa: {qwk:.4f}')\n# 2. Fleiss Kappa (Multi-Rater Table)\n# Misal df_matrix berukuran (N subjek x n rater)\ndata_multi = [\n    [1, 1, 1, 2], [2, 2, 2, 2], [3, 3, 2, 3],\n    [1, 1, 2, 1], [2, 2, 3, 2], [3, 3, 3, 3]\n]\nagg_matrix, _ = aggregate_raters(data_multi)\nf_kappa = fleiss_kappa(agg_matrix)\nprint(f'Fleiss Kappa Multi-Rater: {f_kappa:.4f}')",
             "Bobot 100: Penggunaan cohen_kappa_score weights='quadratic' tepat (45%), penggunaan aggregate_raters & fleiss_kappa tepat (55%).")
        ]
    )

print("modules_part4.py ready...")
